# Keyed Grand Stars
GRAND1 = "Grand Star - World 1"
GRAND2 = "Grand Star - World 2"
GRAND3 = "Grand Star - World 3"
GRAND4 = "Grand Star - World 4"
GRAND5 = "Grand Star - World 5"
GRAND6 = "Grand Star - World 6"
GRAND7 = "Grand Star - World 7"

# Standard items
GRAND = "Grand Star"
POWER = "Power Star"
GREEN = "Green Star"
ONEUP = "1-up Mushroom"

# Consumable Power-Ups
INVINCIBILITY = "Consumable Rainbow Star"
FIREBALLFLO = "Consumable Fire FLower"
BEESHROOM = "Consumable Bee Mushroom"
SPRINGSHROOM = "Consumable Spring Mushroom"
BOOSHROOM = "Consumable Boo Mushroom"
CLOUDFLOW = "Consumable Cloud Flower"
ROCKSHROOM = "Consumable Rock Mushroom"
DRILLHAT = "Consumable Spin Drill"
ICEFLOWER = "Consumable Ice Flower"
REDSTAR = "Consumable Flight Star"

# Power-Up Rando
SUPASTAR    = "Rainbow Star"
FIREFLOWER  = "Fire Flower"
BEEMARIO    = "Bee Mushroom"
SPRING      = "Spring Mushroom"
BOOMARIO    = "Boo Mushroom"
CLOUD       = "Cloud Mushroom"
ROCK        = "Rock Mushroom"
SPINDRILL   = "Spin Drill"

#Unique individual keys
GREENCOMETKEY = "Green Star Comet Key"
GREENCOMETW1 = "Green Star World 1 Key"
GREENCOMETW2 = "Green Star World 2 Key"
GREENCOMETW3 = "Green Star World 3 Key"
GREENCOMETW4 = "Green Star World 4 Key"
GREENCOMETW5 = "Green Star World 5 Key"
GREENCOMETW6 = "Green Star World 6 Key"
GREENCOMETW7 = "Green Star World 7 Key"

# Galaxy Keys
SKYPOBSKEY = "Sky Station Galaxy Key"
FLIPSWAPKEY = "Flip Swap Galaxy Key"
HONEYBLOOMKEY = "Honeybloom Galaxy Key"
BEATBLOCKKEY = "Beat Block Galaxy Key"
SWEETMYSKEY = "Sweet Mystery Galaxy Key"
FLEETGLIDEKEY = "Fleet Glide Galaxy Key"
FLASHBLACKKEY = "Flash Black Galaxy Key"
FLIPOUTKEY = "Flip-Out Galaxy Key"
GOODEGGKEY = "Yoshi Star Galaxy Key"
SPINDIGKEY = "Spin-Dig Galaxy Key"
FLUFFBLUFFKEY = "Fluffy Bluff Galaxy Key"
PUZZPLANKEY = "Puzzle Plank Galaxy Key"
HIGHTAILKEY = "Hightail Falls Galaxy Key"
BOULBOWLKEY = "Boulder Bowl Galaxy Key"
COSMICOKEY = "Cosmic Cove Galaxy Key"
TALLTRUNKKEY = "Tall Trunk Galaxy Key"
CLOUCOURKEY = "Cloudy Court Galaxy Key"
HAUNHALLKEY = "Haunty Halls Galaxy Key"
FREEFLAKEKEY = "Freezy Flake Galaxy Key"
SUPMASSKEY = "Supermassive Galaxy Key"
FLIPVILLKEY = "Flipsville Galaxy Key"
STARBEACHKEY = "Starshine Beach Galaxy Key"
CHOMWORKKEY = "Chompworks Galaxy Key"
SPACSTORKEY = "Space Storm Galaxy Key"
SLIPSANDKEY = "Slipsand Galaxy Key"
SHIVBURNKEY = "Shiverburn Galaxy Key"
BOOMOONKEY = "Boo Moon Galaxy Key"
MELTYKEY = "Melty Monster Galaxy Key"
CLOCKWORKKEY = "Clockwork Ruins Galaxy Key"
WHOMPFORTKEY = "Throwback Galaxy Key"
BATTLEBELTKEY = "Battle Belt Galaxy Key"
MARIOKEY = "Mario Squared Galaxy Key"
ROLLCOASTKEY = "Rolling Coaster Galaxy Key"
TWISTTRIKEY = "Twisty Trials Galaxy Key"
STONECYCKEY = "Stone Cyclone Galaxy Key"
GRANDMASTERKEY = "Grandmaster Galaxy Key"
BOWJR1KEY = "Bowser Jr.'s Fiery Flotilla Key"
BOWJR2KEY = "Bowser Jr.'s Fearsome Fleet Key"
BOWJR3KEY = "Bowser Jr.'s Boom Bunker Key"
BOWSER1KEY = "Bowser's Lava Lair Key"
BOWSER2KEY = "Bowser's Gravity Gauntlet Key"
BOWSER3KEY = "Bowser's Galaxy Generator Key"
BOSSBLITZKEY = "Boss Blitz Galaxy Key"
RIGHTDOWNKEY = "Rightside Down Galaxy Key"
WILDGLIDEKEY = "Wild Glide Galaxy Key"
ROLLMASTKEY = "Rolling Masterpiece Galaxy Key"
HONEYHOPKEY = "Honeyhop Galaxy Key"
UPDOWNKEY = "Upside Dizzy Galaxy Key"
SLIMSPRIKEY = "Slimy Spring Galaxy Key"