# Sky Station Star locations
SKYSTASTAR1 = "Sky Station 1: Peewee Pirahna's Temper Tantrum"
SKYSTASTAR2 = "Sky Station 2: Storming the Sky Fleet"
SKYSTASTAR3 = "Sky Station Comet: Peewee Piranha's Speed Run"
SKYSTASTARG1 = "Sky Station: Green Star 1"
SKYSTASTARG2 = "Sky Station: Green Star 2"
SKYSTASTARG3 = "Sky Station: Green Star 3"

# Yoshi Star Star Locations
YOSHSTARSTAR1 = "Yoshi Star 1: Saddle Up With Yoshi"
YOSHSTARSTAR2 = "Yoshi Star 2: Spiny Control"
YOSHSTARSTAR3 = "Yoshi Star Comet: Spiny Rainbow Romp"
YOSHSTARSTARG1 = "Yoshi Star: Green Star 1"
YOSHSTARSTARG2 = "Yoshi Star: Green Star 2"
YOSHSTARSTARG3 = "Yoshi Star: Green Star 3"

# Spin-Dig Star Locations
SPINDIGSTAR1 = "Spin-Dig 1: Digga-Leg's Planet"
SPINDIGSTAR2 = "Spin-Dig 2: Silver Stars Down Deep"
SPINDIGSTAR3 = "Spin-Dig Comet: Digga-Leg's Daredevil Run"
SPINDIGSTARG1 = "Spin-Dig: Green Star 1"
SPINDIGSTARG2 = "Spin-Dig: Green Star 2"
SPINDIGSTARG3 = "Spin-Dig: Green Star 3"

# Fluffy Bluff Star Locations
FLUFBLUFSTAR1 = "Fluffy Bluff: Search for the Toad Brigade Captain"
FLUFBLUFSTAR2 = "Fluffy Bluff Chimp: The Chimp's Stomp Challenge"
FLUFBLUFSTAR3 = "Fluffy Bluff Hungry Luma: Every Planet Has Its Price"
FLUFBLUFSTARG1 = "Fluffy Bluff: Green Star 1"
FLUFBLUFSTARG2 = "Fluffy Bluff: Green Star 2"
FLUFBLUFSTARG3 = "Fluffy Bluff: Green Star 3"

# Rightside Down Star Locations
RIGHTDOWNSTAR1 = "Rightside Down: Breaking the Laws of Gravity"
RIGHTDOWNSTAR2 = "Rightside Down Secret: The Great Crate Incinerator"
RIGHTDOWNSTARG1 = "Rightside Down: Green Star 1"
RIGHTDOWNSTARG2 = "Rightside Down: Green Star 2"

# Flip-Swap Star Locations
FLIPSWAPSTAR1 = "Flip-Swap: Think Before You Shake"
FLIPSWAPSTAR2 = "Flip-Swap Comet: Purple Coin Flip 'n' Sprint"
FLIPSWAPSTARG1 = "Flip-Swap: Green Star 1"
FLIPSWAPSTARG2 = "Flip-Swap: Green Star 2"

# Bowser Jr.s Fiery Flotilla
FIREFLOTSTAR1 = "Fiery Flotilla: Gobblegut's Aching Belly"
FIREFLOTSTAR2 = "Fiery Flotilla Comet: Fiery Flotilla Speed Run"
FIREFLOTSTARG1 = "Fiery Flotilla: Green Star 1"
FIREFLOTSTARG2 = "Fiery Flotilla: Green Star 2"

# World 2
# Puzzle Plank Star Locations
PUZZPLANKSTAR1 = "Puzzle Plank: The Puzzling Picture Block"
PUZZPLANKSTAR2 = "Puzzle Plank Comet: Purple Coin Shadow Vault"
PUZZPLANKSTAR3 = "Puzzle Plank Hungry Luma: Bugaboom's Back"
PUZZPLANKSTARG1 = "Puzzle Plank: Green Star 1"
PUZZPLANKSTARG2 = "Puzzle Plank: Green Star 2"
PUZZPLANKSTARG3 = "Puzzle Plank: Green Star 3"

# Hightail Falls Star Locations
HIGHFALLSTAR1 = "Hightail Falls: Hot-Stepping Dash Pepper"
HIGHFALLSTAR2 = "Hightail Falls Comet: Hightail Falls Speed Run"
HIGHFALLSTAR3 = "Hightail Falls Hungry Luma: Silver Stars in Hightail Falls"
HIGHFALLSTARG1 = "Hightail Falls: Green Star 1"
HIGHFALLSTARG2 = "Hightail Falls: Green Star 2"
HIGHFALLSTARG3 = "Hightail Falls: Green Star 3"

# Boulder Bowl Star Locations
ROCKBOWLSTAR1 = "Boulder Bowl: Rock and Rollodillo"
ROCKBOWLSTAR2 = "Boulder Bowl Comet: Rolling Crabber Romp"
ROCKBOWLSTAR3 = "Boulder Bowl Secret: C'mere, Goomba"
ROCKBOWLSTARG1 = "Boulder Bowl: Green Star 1"
ROCKBOWLSTARG2 = "Boulder Bowl: Green Star 2"
ROCKBOWLSTARG3 = "Boulder Bowl: Green Star 3"

# Cosmic Cove Star Locations
COSCCOVESTAR1 = "Cosmic Cove 1: Twin Falls Hideaway"
COSCCOVESTAR2 = "Cosmic Cove 2: Exploring the Cosmic Cavern"
COSCCOVESTAR3 = "Cosmic Cove Hungry Luma: Catch That Star Bunny"
COSCCOVESTARG1 = "Cosmic Cove: Green Star 1"
COSCCOVESTARG2 = "Cosmic Cove: Green Star 2"
COSCCOVESTARG3 = "Cosmic Cove: Green Star 3"

# Wild Glide Star Locations
WILDGLIDESTAR1 = "Wild Glide 1: Fluzzard's First Flight"
WILDGLIDESTAR2 = "Wild Glide 2: Jungle Fluzzard Race"
WILDGLIDESTARG1 = "Wild Glide: Green Star 1"
WILDGLIDESTARG2 = "Wild Glide: Green Star 2"

# Honeybloom Star Locations
BEEBLOOMSTAR1 = "Honeybloom: Bumble Beginnings"
BEEBLOOMSTAR2 = "Honeybloom Secret: The Secret Wall Jump"
BEEBLOOMSTARG1 = "Honeybloom: Green Star 1"
BEEBLOOMSTARG2 = "Honeybloom: Green Star 2"

# Bowser's Lava Lair Star Locations
LAVALAIRSTAR1 = "Lava Lair: Bowser's Big Lava Power Party"
LAVALAIRSTAR2 = "Lava Lair Comet: Lava Lair Speed Run"
LAVALAIRSTARG1 = "Lava Lair: Green Star 1"
LAVALAIRSTARG2 = "Lava Lair: Green Star 2"

# World 3
# Tall Trunk Star Locations
TALLTREESTAR1 = "Tall Trunk 1: The Flotacious Blimp Fruit"
TALLTREESTAR2 = "Tall Trunk 2: Tall Trunk's Big Slide"
TALLTREESTAR3 = "Tall Trunk Comet: Tall Trunk's Purple Coin Slide"
TALLTREESTARG1 = "Tall Trunk: Green Star 1"
TALLTREESTARG2 = "Tall Trunk: Green Star 2"
TALLTREESTARG3 = "Tall Trunk: Green Star 3"

# Cloudy Court Star Locations
CLOUDCOURTSTAR1 = "Cloudy Court: Head in the Clouds"
CLOUDCOURTSTAR2 = "Cloudy Court Comet: The Shadow Lining"
CLOUDCOURTSTAR3 = "Cloudy Court Hungry Luma: Silver Stars in the Purple Pond"
CLOUDCOURTSTARG1 = "Cloudy Court: Green Star 1"
CLOUDCOURTSTARG2 = "Cloudy Court: Green Star 2"
CLOUDCOURTSTARG3 = "Cloudy Court: Green Star 3"

# Haunty Halls Star Locations
HAUNTHALLSTAR1 = "Haunty Halls 1: A Glimmer of Bulb Berry"
HAUNTHALLSTAR2 = "Haunty Halls 2: Sneaking Down the Creepy Corridor"
HAUNTHALLSTAR3 = "Haunty Halls Comet: Spooky Cosmic Clone Chase"
HAUNTHALLSTARG1 = "Haunty Halls: Green Star 1"
HAUNTHALLSTARG2 = "Haunty Halls: Green Star 2"
HAUNTHALLSTARG3 = "Haunty Halls: Green Star 3"

# Freezy Flake Star Locations
SNOWFLAKESTAR1 = "Freezy Flake 1: Bowser on Ice"
SNOWFLAKESTAR2 = "Freezy Flake 2: Sorbetti's Chilly Reception"
SNOWFLAKESTAR3 = "Freezy Flake Chimp: The Chimp's Skating Challenge"
SNOWFLAKESTARG1 = "Freezy Flake: Green Star 1"
SNOWFLAKESTARG2 = "Freezy Flake: Green Star 2"
SNOWFLAKESTARG3 = "Freezy Flake: Green Star 3"

# Rolling Masterpiece Star Locations
ROLLMASTERSTAR1 = "Rolling Masterpiece: Silver Chomp Grudge Match"
ROLLMASTERSTAR2 = "Rolling Masterpiece Comet: Masterpiece Speed Run"
ROLLMASTERSTARG1 = "Rolling Masterpiece: Green Star 1"
ROLLMASTERSTARG2 = "Rolling Masterpiece: Green Star 2"

# Beat Block Star Locations
BEATBLOCKSTAR1 = "Beat Block: Step to the Beep"
BEATBLOCKSTAR2 = "Beat Block Comet: Silver Stars in Double Time"
BEATBLOCKSTARG1 = "Beat Block: Green Star 1"
BEATBLOCKSTARG2 = "Beat Block: Green Star 2"

# Bowser Jr.'s Fearsome Fleet
FEARFLETSTAR1 = "Fearsome Fleet: Bowser Jr's Mighty Megahammer"
FEARFLETSTAR2 = "Fearsome Fleet Comet: Megahammer's Daredevil Bash"
FEARFLETSTARG1 = "Fearsome Fleet: Green Star 1"
FEARFLETSTARG2 = "Fearsome Fleet: Green Star 2"

# World 4
# Supermassive Star Locations
SUPERMASSSTAR1 = "Supermassive: Huge Trouble with Big Wigglers"
SUPERMASSSTAR2 = "Supermassive Comet: Big Wigglers Speed Run"
SUPERMASSSTAR3 = "Supermassive Secret: In Full Bloom"
SUPERMASSSTARG1 = "Supermassive: Green Star 1"
SUPERMASSSTARG2 = "Supermassive: Green Star 2"
SUPERMASSSTARG3 = "Supermassive: Green Star 3"

# Flipsville Star Locations
FLIPVILLESTAR1 = "Flipsville 1: Flip-Flopping in Flipsville"
FLIPVILLESTAR2 = "Flipsville 2: Flipsville's New Digs"
FLIPVILLESTAR3 = "Flipsville Comet: Purple Coin Spin Speed Run"
FLIPVILLESTARG1 = "Flipsville: Green Star 1"
FLIPVILLESTARG2 = "Flipsville: Green Star 2"
FLIPVILLESTARG3 = "Flipsville: Green Star 3"

# Starshine Beach Star Locations
STARBEACHSTAR1 = "Starshine Beach 1: Surf, Sand, and Silver Stars"
STARBEACHSTAR2 = "Starshine Beach 2: Climbing the Cloudy Tower"
STARBEACHSTAR3 = "Starshine Beach Comet: Purple Coin Beach Dash"
STARBEACHSTARG1 = "Starshine Beach: Green Star 1"
STARBEACHSTARG2 = "Starshine Beach: Green Star 2"
STARBEACHSTARG3 = "Starshine Beach: Green Star 3"

# Chompworks Star Locations
CHOMPWORKSTAR1 = "Chompworks 1: Where the Chomps Are Made of Gold"
CHOMPWORKSTAR2 = "Chompworks 2: Spring Into the Chompworks"
CHOMPWORKSTAR3 = "Chompworks Comet: Cosmic Clones in the Chompworks"
CHOMPWORKSTARG1 = "Chompworks: Green Star 1"
CHOMPWORKSTARG2 = "Chompworks: Green Star 2"
CHOMPWORKSTARG3 = "Chompworks: Green Star 3"

# Honeyhop Star Locations
HONEYHOPSTAR1 = "Honeyhop: The Sweetest Silver Stars"
HONEYHOPSTAR2 = "Honeyhop Chimp: The Chimp's Score Challenge"
HONEYHOPSTARG1 = "Honeyhop: Green Star 1"
HONEYHOPSTARG2 = "Honeyhop: Green Star 2"

# Sweet Mystery Star Locations
SWEETMYSTSTAR1 = "Sweet Mystery: Bulb Berry's Mysterious Glow"
SWEETMYSTSTAR2 = "Sweet Mystery Comet: Bulb Berry's Purple Coin Glow"
SWEETMYSTSTARG1 = "Sweet Mystery: Green Star 1"
SWEETMYSTSTARG2 = "Sweet Mystery: Green Star 2"

# Bowser's Gravity Gauntlet Star Locations
GRAVGAUNSTAR1 = "Gravity Gauntlet: Breaking Into Bowser's Castle"
GRAVGAUNSTAR2 = "Gravity Gauntlet Comet: Gravity Star Speed Run"
GRAVGAUNSTARG1 = "Gravity Gauntlet: Green Star 1"
GRAVGAUNSTARG2 = "Gravity Gauntlet: Green Star 2"

# World 5
# Space Storm Star Locations
SPACESTORMSTAR1 = "Space Storm 1: Follow Me, Bob-Omb"
SPACESTORMSTAR2 = "Space Storm 2: To the Top of Topman's Tower"
SPACESTORMSTAR3 = "Space Storm Secret: C'mere, Topman"
SPACESTORMSTARG1 = "Space Storm: Green Star 1"
SPACESTORMSTARG2 = "Space Storm: Green Star 2"
SPACESTORMSTARG3 = "Space Storm: Green Star 3"

# Slipsand Star Locations
SLIPSANDSTAR1 = "Slipsand 1: Squizzard's Sandy Sinkhole"
SLIPSANDSTAR2 = "Slipsand 2: Sailing the Sandy Seas"
SLIPSANDSTAR3 = "Slipsand Comet: Squizzard's Daredevil Run"
SLIPSANDSTARG1 = "Slipsand: Green Star 1"
SLIPSANDSTARG2 = "Slipsand: Green Star 2"
SLIPSANDSTARG3 = "Slipsand: Green Star 3"

# Shiverburn Star Locations
COLDFIRESTAR1 = "Shiverburn: Prince Pikante's Peppery Mood"
COLDFIRESTAR2 = "Shiverburn Comet: Octo-Army Icy Rainbow Romp"
COLDFIRESTAR3 = "Shiverburn Chimp: The Chimp's Ultimate Skating Challenge"
COLDFIRESTARG1 = "Shiverburn: Green Star 1"
COLDFIRESTARG2 = "Shiverburn: Green Star 2"
COLDFIRESTARG3 = "Shiverburn: Green Star 3"

# Boo Moon Star Locations
BOOMOONSTAR1 = "Boo Moon 1: Silver Stars Pop-Up"
BOOMOONSTAR2 = "Boo Moon 2: Haunting the Howling Tower"
BOOMOONSTAR3 = "Boo Moon Secret: The Star in the Sinking Swamp"
BOOMOONSTARG1 = "Boo Moon: Green Star 1"
BOOMOONSTARG2 = "Boo Moon: Green Star 2"
BOOMOONSTARG3 = "Boo Moon: Green Star 3"

# Upside Dizzy Star Locations
UPDIZZYSTAR1 = "Upside Dizzy: A Walk on the Weird Side"
UPDIZZYSTAR2 = "Upside Dizzy Secret: Burning Upside Dizzy"
UPDIZZYSTARG1 = "Upside Dizzy: Green Star 1"
UPDIZZYSTARG2 = "Upside Dizzy: Green Star 2"

# Fleet Glide Star Locations
FLEETFLYSTAR1 = "Fleet Glide 1: Fluzzard's Wild Battlefield Glide"
FLEETFLYSTAR2 = "Fleet Glide 2: Fastest Feathers in the Galaxy"
FLEETFLYSTARG1 = "Fleet Glide: Green Star 1"
FLEETFLYSTARG2 = "Fleet Glide: Green Star 2"

# Bowser Jr.'s Boom Bunker Star Locations
BOOMBUNKSTAR1 = "Boom Bunker: Bowser Jr.'s Boomsday Machine"
BOOMBUNKSTAR2 = "Boom Bunker Comet: Boomsday Machine Daredevil Run"
BOOMBUNKSTARG1 = "Boom Bunker: Green Star 1"
BOOMBUNKSTARG2 = "Boom Bunker: Green Star 2"

# World 6
# Melty Monster Star Locations
MELTMONSSTAR1 = "Melty Monster 1: The Magnificent Magma Sea"
MELTMONSSTAR2 = "Melty Monster 2: A Stroll Down Rolling Lane"
MELTMONSSTAR3 = "Melty Monster Chimp: The Chimp's Bowling Challenge"
MELTMONSSTARG1 = "Melty Monster: Green Star 1"
MELTMONSSTARG2 = "Melty Monster: Green Star 2"
MELTMONSSTARG3 = "Melty Monster: Green Star 3"

# Clockwork Ruins Star Locations
CLOCKRUINSTAR1 = "Clockwork Ruins 1: Time for Adventure"
CLOCKRUINSTAR2 = "Clockwork Ruins Comet: The Adventure of the Purple Coins"
CLOCKRUINSTAR3 = "Clockwork Ruins Hungry Luma: The Ledge Hammer Trap"
CLOCKRUINSTARG1 = "Clockwork Ruins: Green Star 1"
CLOCKRUINSTARG2 = "Clockwork Ruins: Green Star 2"
CLOCKRUINSTARG3 = "Clockwork Ruins: Green Star 3"

# Throwback Star Locations
THROWBACKSTAR1 = "Throwback 1: Return of the Whomp King"
THROWBACKSTAR2 = "Throwback 2: Silver Stars in the Whomp Fortress"
THROWBACKSTAR3 = "Throwback Comet: Whomp Silver Star Speed Run"
THROWBACKSTARG1 = "Throwback: Green Star 1"
THROWBACKSTARG2 = "Throwback: Green Star 2"
THROWBACKSTARG3 = "Throwback: Green Star 3"

# Battle Belt Star Locations
BATTBELTSTAR1 = "Battle Belt: Mini-Planet Mega-Run"
BATTBELTSTAR2 = "Battle Belt Comet: Mini-Planet Daredevil Run"
BATTBELTSTAR3 = "Battle Belt Hungry Luma: Snacktime for Gobblegut"
BATTBELTSTARG1 = "Battle Belt: Green Star 1"
BATTBELTSTARG2 = "Battle Belt: Green Star 2"
BATTBELTSTARG3 = "Battle Belt: Green Star 3"

# Flash Black Star Locations
FLASHBLACKSTAR1 = "Flash Black: Jumping Around in the Dark"
FLASHBLACKSTAR2 = "Flash Black Comet: Dark Octo-Army Romp"
FLASHBLACKSTARG1 = "Flash Black: Green Star 1"
FLASHBLACKSTARG2 = "Flash Black: Green Star 2"

# Slimy Spring Star Locations
SLIMYSPRISTAR1 = "Slimy Spring: The Deep Shell Well"
SLIMYSPRISTAR2 = "Slimy Spring Chimp: The Chimp's Coin Challenge"
SLIMYSPRISTARG1 = "Slimy Spring: Green Star 1"
SLIMYSPIRSTARG2 = "Slimy Spring: Green Star 2"

# Bowser's Galaxy Generator Star Locations
GALAXYGENSTAR1 = "Galaxy Generator: Bowser's Fortified Fortress"
GALAXYGENSTAR2 = "Galaxy Generator Comet: Bowser's Big Bad Speed Run"
GALAXYGENSTARG1 = "Galaxy Generator: Green Star 1"
GALAXYGENSTARG2 = "Galaxy Generator: Green Star 2"

# World S
# Mario Squared Star Locations
MARIOSQRSTAR1 = "Mario Squared : Make Mario a Star"
MARIOSQRSTAR2 = "Mario Squared Comet: Luigi's Purple Coin Chaos"
MARIOSQRSTARG1 = "Mario Squared: Green Star 1"
MARIOSQRSTARG2 = "Mario Squared: Green Star 2"

# Rolling Coaster Star Locations
ROLLSLIDESTAR1 = "Rolling Coaster: The Rainbow Road Roll"
ROLLSLIDESTAR2 = "Rolling Coaster Comet: Purple Coins on the Rainbow Road"
ROLLSLIDESTARG1 = "Rolling Coaster: Green Star 1"
ROLLSLIDESTARG2 = "Rolling Coaster: Green Star 2"

# Twisty Trials Star Locations
TWISTTRIALSTAR1 = "Twisty Trials: Spinning and Spinning and Spinning"
TWISTTRIALSTAR2 = "Twisty Trials Comet: Turning Turning Double Time"
TWISTTRIALSTARG1 = "Twisty Trial: Green Star 1"
TWISTTRIALSTARG2 = "Twisty Trial: Green Star 2"

# Stone Cyclone Star Locations
STONECYCLOSTAR1 = "Stone Cyclone: Silver Stars on the Cyclone"
STONECYCLOSTAR2 = "Stone Cyclone Comet: Tox Box Speed Run"
STONECYCLOSTARG1 = "Stone Cyclone: Green Star 1"
STONECYCLOSTARG2 = "Stone Cyclone: Green Star 2"

# Boss Blitz Star Locations
BOSSBLITSTAR1 = "Boss Blitz: Throwback Throwdown"
BOSSBLITSTAR2 = "Boss Blitz Comet: Throwback Throwdown Speed Run"
BOSSBLITSTARG1 = "Boss Blitz: Green Star 1"
BOSSBLITSTARG2 = "Boss Blitz: Green Star 2"

# Flip-Out Star Locations
FLIPOUTSTAR1 = "Flip-Out: Wicked Wall Jumps"
FLIPOUTSTAR2 = "Flip-Out Comet: Cosmic Clone Wall Jumpers"
FLIPOUTSTARG1 = "Flip-Out: Green Star 1"
FLIPOUTSTARG2 = "Flip-Out: Green Star 2"

# Grandmaster
GRANDMASTSTAR1 = "Grandmaster: The Ultimate Test"
GRANDMASTSTAR2 = "Grandmaster Comet: The Perfect Run"

# World 1 Comet Medals
SKYSTACM = "Sky Station Comet Medal"
YOSHSTARCM = "Yoshi Star Comet Medal"
SPINDIGCM = "Spin-Dig Comet Medal"
FLUFBLUFCM = "Fluffy Bluff Comet Medal"
RIGHTDOWNCM = "Rightside Down Comet Medal"
FLIPSWAPCM = "Flip-Swap Comet Medal"
FIREFLOTCM = "Fiery Flotilla Comet Medal"

# World 2 Comet Medals
PUZZPLANKCM = "Puzzle Plank Comet Medal"
HIGHFALLCM = "Hightail Falls Comet Medal"
ROCKBOWLCM = "Boulder Bowl Comet Medal"
COSCCOVECM = "Cosmic Cove Comet Medal"
WILDGLIDECM = "Wild Glide Comet Medal"
BEEBLOOMCM = "Honeybloom Comet Medal"
LAVALAIRCM = "Lava Lair Comet Medal"

# World 3 Comet Medals
TALLTREECM = "Tall Trunk Comet Medal"
CLOUDCOURTCM = "Cloudy Court Comet Medal"
HAUNTHALLCM = "Haunty Halls Comet Medal"
SNOWFLAKECM = "Freezy Flake Comet Medal"
ROLLMASTERCM = "Rolling Masterpiece Comet Medal"
BEATBLOCKCM = "Beat Block Comet Medal"
FEARFLEETCM = "Fearsome Fleet Comet Medal"

# World 4 Comet Medals
SUPERMASSCM = "Supermassive Comet Medal"
FLIPVILLECM = "Flipsville Comet Medal"
STARBEACHCM = "Starshine Beach Comet Medal"
CHOMPWORKCM = "Chompworks Comet Medal"
HONEYHOPCM = "Honeyhop Comet Medal"
SWEETMYSTCM = "Sweet Mystery Comet Medal"
GRAVGAUNTCM = "Gravity Gauntlet Comet Medal"

# World 5 Comet Medals
SPACESTORMCM = "Space Storm Comet Medal"
SLIPSANDCM = "Slipsand Comet Medal"
COLDFIRECM = "Shiverburn Comet Medal"
BOOMOONCM = "Boo Moon Comet Medal"
UPDIZZYCM = "Upside Dizzy Comet Medal"
FLEETFLYCM = "Fleet Glide Comet Medal"
BOOMBUNKCM = "Boom Bunker Comet Medal"

# World 6 Comet Medals
MELTMONSCM = "Melty Monster Comet Medal"
CLOCKRUINSCM = "Clockwork Ruins Comet Medal"
THROWBACKCM = "Throwback Comet Medal"
BATTBELTCM = "Battle Belt Comet Medal"
FLASHBLACKCM = "Flash Black Comet Medal"
SLIMYSPRICM = "Slimy Spring Comet Medal"
GLXYGENCM = "Galaxy Generator Comet Medal"

# World S Comet Medals
MARIOSQRCM = "Mario Squared Comet Medal"
ROLLSLIDECM = "Rolling Coaster Comet Medal"
TWISTTRIALCM = "Twisty Trials Comet Medal"
STONECYCLOCM = "Stone Cyclone Comet Medal"
BOSSBLITCM = "Boss Blitz Comet Medal"
FLIPOUTCM = "Flip-Out Comet Medal"
GRANDMASTRCM = "Grandmaster Comet Medal"

# World 1 Checkpoints
SKYOBS1GREENHILLCP = "Sky Station 1: Green Hill Planet Checkpoint"
SKYOBS1CYLINDERCP = "Sky Station 1: Cylindrical Planet Checkpoint"
SKYOBS1BEFOREBOSSCP = "Sky Station 1: Two-Sided Planet Checkpoint"
SKYOBS2SKYFLEETCP = "Sky Station 2: Sky Fleet Cylinder Checkpoint"
SKYOBS2FLIPSWITCHCP = "Sky Station 2: Flipswitch Fleet Checkpoint"
SKYOBS2GRASSFLEETCP = "Sky Station 2: Grassy Fleet Ship"
GOODEGG1EARTHCP = "Yoshi Star 1: Earthy Planet Checkpoint"
GOODEGG1FOSSILCP = "Yoshi Star 1: Fossil Wall Checkpoint"
GOODEGG2SHOOTINGCP = "Yoshi Star 2: Spiny Shooting Gallery Checkpoint"
GOODEGG2BOSSCP = "Yoshi Star 2: King Lakitu Planet Checkpoint"
SPINDIG1STEELCP = "Spin-Dig 1: Steel Ring Planet Checkpoint"
SPINDIG1TOADSCP = "Spin-Dig 1: Red Toadship Checkpoint"
SPINDIG2BTOADCP = "Spin-Dig 2: Blue Toadship Checkpoint"
FLUFFBLUFF1CLIFF1CP = "Fluffy Bluff: Checkpoint Cliff Checkpoint"
FLUFFBLUFF1CLOUDCLIMBCP = "Fluffy Bluff: Cloud Climb Checkpoint"
FLUFFBLUFF3TOWERCP = "Fluffy Bluff Hungry Luma: Cone Tower Checkpoint"
FLIPSWAP1CP = "Flip-Swap: Mid-Level Checkpoint"
RIGHTDOWNCORRIDORCP1 = "Rightside Down: Main Corridor Checkpoint 1"
RIGHTDOWNCORRIDORCP2 = "Rightside Down: Main Corridor Checkpoint 2"
RIGHTDOWNCORRIDORCP3 = "Rightside Down: Main Corridor Checkpoint 3"
FIREFLOT1LAVACP = "Fiery Flotilla: Lava Planet Checkpoint"

# World 2 Checkpoints
PUZZPLAN1SAWBLACP = "Puzzle Plank: Saws & Planks Checkpoint"
PUZZPLAN1CHECKPCP = "Puzzle Plank: Checkpoint Planet Checkpoint"
PUZZPLAN3BUGABOCP = "Puzzle Plank Hungry Luma: Bugaboom Tree Checkpoint"
HIGHTAIL1PLATDASCP = "Hightail Falls: Hot Pepper Dash Checkpoint"
HIGHTAIL1DASHWALCP = "Hightail Falls: Hot Pepper Wall Checkpoint"
BOULBOWL1FALLINGCP = "Boulder Bowl: Falling Rocks Planet Checkpoint"
BOULBOWL1DODECAHCP = "Boulder Bowl: Dodecahedron Planet Checkpoint"
COSMIC3WATERCP = "Cosmic Cove Hungry Luma: Holey Water Planet Checkpoint"
COSMIC2INPIPECP = "Cosmic Cove 2: Inside Pipe Checkpoint"
COSMIC2WATERPACP = "Cosmic Cove 2: Water Path Checkpoint"
COSMIC2TOADSHICP = "Cosmic Cove 2: Red Toadship Checkpoint"
HONEYBLOOM1WALL2CP = "Honeybloom: Bee Cloud Climb Checkpoint"
HONEYBLOOM1WALL3CP = "Honeybloom: Bubble Bee Shrooms Checkpoint"
HONEYBLOOM1HONELOGCP = "Honeybloom: Honeycomb Log Checkpoint"
LAVALAIR1LAVAPLA1CP = "Lava Lair: Lava Planet 1 Checkpoint"
LAVALAIR1LAVAPLA2CP1 = "Lava Lair: Lava Planet 2 Start Checkpoint"
LAVALAIR1LAVAPLA2CP2 = "Lava Lair: Lava Planet 2 Before Boss Checkpoint"

# World 3 Checkpoints
TALLTRUNK1LOGCP = "Tall Trunk 1: Carved Log Planet Checkpoint"
TALLTRUNK1WOODCIRClECP = "Tall Trunk 1: Wood Circle Planet Checkpoint"
TALLTRUNK2SLIDECP = "Tall Trunk 2: Log Slide Checkpoint"
CLOUCOUR1TOWERSCP = "Cloudy Court: Ruined Towers Checkpoint"
CLOUCOUR1CASTLECP = "Cloudy Court: Castle Wall Checkpoint"
CLOUCOUR3PCOINSCP = "Cloudy Court Hungry Luma: Purple Pond Checkpoint"
HAUNHALL1DISAPPECP = "Haunty Halls 1: Disappearing Hallway Checkpoint"
HAUNHALL1BULBBERCP = "Haunty Halls 1: Bulb Berry Room Checkpoint"
HAUNHALL2CREEPYCCP = "Haunty Halls 2: Creepy Platforms Checkpoint"
HAUNHALL2CREEPYHCP = "Haunty Halls 2: Creepy Corridor Checkpoint"
FREEFLAK1SNOWBYHCP = "Freezy Flake 1: Snowy Hill Planet Checkpoint"
FREEFLAK1LAVASNOCP = "Freezy Flake 1: Snow-Lava Planet Checkpoint"
FREEFLAK2WHITOUTCP1 = "Freezy Flake 2: Whiteout Planet Starting Checkpoint"
FREEFLAK2WHITOUTCP2 = "Freezy Flake 2: Whiteout Planet Ending Checkpoint"
ROLLMAST1ELEVATOCP = "Rolling Masterpiece: Elevator Planet Checkpoint"
ROLLMAST1SAWBLADCP = "Rolling Masterpiece: Bob-omb Planet Checkpoint"
BEATBLOK1CP = "Beat Block: Blocks on the Beats Checkpoint"
BEATBLOK2CP1 = "Beat Block Comet: Beats on the Blocks First Checkpoint"
BEATBLOK2CP2 = "Beat Block Comet: Beats on the Blocks Second Checkpoint"
FEARFLET1BULLETBCP = "Fearsome Fleet: Bullet Bill Platform Checkpoint"
FEARFLET1AIRSHIPCP = "Fearsome Fleet: Airship Autoscroller Checkpoint"

# World 4 Checkpoints
SUPMASS1THWOMPSCP = "Supermassive: Giant Thwomps Checkpoint"
SUPMASS1STARCHIPSCP = "Supermassive: Giant Star Chips Checkpoint"
SUPMASS1WIGGLERSCP = "Supermassive: Big Wigglers Checkpoint"
FLIPVILL1WANWANCP = "Flipsville 1: Chomp Planet Checkpoint"
FLIPVILL1LIFTCP = "Flipsville 1: Lift Section Checkpoint"
FLIPVILL1STARSHROOMCP = "Flipsville 1: Starshroom Checkpoint"
FLIPVILL2TOWERSTARTCP = "Flipsville 2: Spin-Drill Tower Checkpoint"
CHOMWORK1ROLLINGCP = "Chompworks 1: Rolling Chomps Planet Checkpoint"
CHOMWORK1LAVACP = "Chompworks 1: Lava Chomp Planet Checkpoint"
CHOMWORK2ROLLINGCP = "Chompworks 2: Rolling Chomps Planet Checkpoint"
CHOMWORK2TOWERCP = "Chompworks 2: Spring Tower Checkpoint"
SWEETMYS1COOKIECP = "Sweet Mystery: Cookie End Checkpoint"
SWEETMYS1SWITCHESCP = "Sweet Mystery: Flipswitch Panel Checkpoint"
SWEETMYS1CAKECP = "Sweet Mystery: Final Cake Planet Checkpoint"
HONEYHOP1QBBASECP = "Honeyhop: Queen Bee Planet Checkpoint"
GRAVGAUN1LANDINGCP = "Gravity Gauntlet: Before Water Checkpoint"
GRAVGAUN1WHOMPWACP = "Gravity Gauntlet: Whomp Walls Checkpoint"
GRAVGAUN1DOORTODCP = "Gravity Gauntlet: Before Bowser Door Checkpoint"

# World 5 Checkpoints
SPACSTOR1TOPMANCP = "Space Storm 1: Top Man Planet Checkpoint"
SPACSTOR2TOPTOWERCP = "Space Storm 2: Topman Tower Checkpoint"
SLIPSAND1CUBECP = "Slipsand 1: Sand Cube Planet Checkpoint"
SLIPSAND1SLIDECP = "Slipsand 1: Pyramid Slide Planet Checkpoint"
SLIPSAND2BIRDCP = "Slipsand 2: Sand Bird Checkpoint"
SHIVBURN1LAVACP = "Shiverburn: Lava Ball Planet Checkpoint"
SHIVBURN1FIREICECP = "Shiverburn: Lava Ice Path Checkpoint"
SHIVBURN1TOADCP = "Shiverburn: Green Toadship Checkpoint"
BOOMOON1POISONCP = "Boo Moon 1: Poison Swamp Checkpoint"
BOOMOON2TOWERCP = "Boo Moon 2: Howling Tower Checkpoint"
UPDOWNINSIDECP = "Upside Dizzy: Castle Interior Checkpoint"
BOOMBUNK1CHECKCP = "Boom Bunker: Checkpoint Sphere Checkpoint"
BOOMBUNK2DARKCP = "Boom Bunker Comet: Dark Matter Planet Checkpoint"

# World 6 Checkpoints
MELTY1LAVAWAVE1CP = "Melty Monster 1: Lava Wave Landing Checkpoint"
MELTY1LAVAWAVE3CP = "Melty Monster 1: Lava Wave Before Tornadoes Checkpoint"
MELTY2BOWLINGCP = "Melty Monster 2: Bowling Platforms Checkpoint"
MELTY3CHIMPCP = "Melty Monster Chimp: Chimp Bowling Challenge Checkpoint"
CLOCKWORK1PUSHCP = "Clockwork Ruins: Push Block Planet Checkpoint"
CLOCKWORK1WHEELSCP = "Clockwork Ruins: Rolling Wheels Planet Checkpoint"
CLOCKWORK3HAMMERCP = "Clockwork Ruins Hungry Luma: Hammer Checkpoint"
WHOMP1FORTCP = "Throwback 1: Whomp's Fortress Checkpoint"
BATTBELT1PTOACP = "Battle Belt: Pink Toadship Checkpoint"
BATTBELT1RTOACP = "Battle Belt: Red Toadship Checkpoint"
BATTBELT2PTOACP = "Battle Belt Comet: Yellow Toadship Checkpoint"
BATTBELT2RTOACP = "Battle Belt Comet: Red Toadship Checkpoint"
FLASHBLACK1PATHCP = "Flash Black: Flash Black Path Checkpoint"
SLIMSPRI1MOUTH2CP = "Slimy Spring: Tower Drop Checkpoint"
GALGEN1LAVACYLCP = "Galaxy Generator: Lava Cylinder Checkpoint"
GALGEN1TOWERCP = "Galaxy Generator: Tower Planet Checkpoint"
GALGEN1YOSHICP = "Galaxy Generator: Yoshi Platform Checkpoint"
GALGEN1STATUECP = "Galaxy Generator: Bowser Statue Checkpoint"
GALGEN2YOSHICP = "Galaxy Generator Comet: Yoshi Platform Checkpoint"

# World S(7) Checkpoints
TWISTY2PLAT2CP = "Twisty Trials Comet: Walls Platform Checkpoint"
BOSSBLITZ1BOULDERCP = "Boss Blitz: Bouldergeist Checkpoint"
FLIPOUT1CLIMBCP1 = "Flip-Out: Flip-Out Climb First Checkpoint"
FLIPOUT1CLIMBCP2 = "Flip-Out: Flip-Out Climb Second Checkpoint"
FLIPOUT2CLIMBCP1 = "Flip-Out Comet: Flip-Out Climb First Checkpoint"
FLIPOUT2CLIMBCP2 = "Flip-Out Comet: Flip-Out Climb Second Checkpoint"
GRANDMASTER1CLOUDCP = "Grandmaster: Electric Clouds Checkpoint"
GRANDMASTER1SWAPCP = "Grandmaster: Flip-Swap Lane Checkpoint"
GRANDMASTER1PULLCP = "Grandmaster: Pull Star Path Checkpoint"

# Mailtoad Letters
GOLDGEARMO = "Letter from Gold Gearmo"
SILVGEARMO = "Letter from Silver Gearmo"
JIBBERJAY1 = "Letter from Jibberjay: Jungle Fluzzard Race"
JIBBERJAY2 = "Letter from Jibberjay: Fastest Feathers in the Galaxy"
CHIMPSTOMP = "Letter from The Chimp: Fluffy Bluff Stomp Challenge"
CHIMPSCORE = "Letter from The Chimp: Honeyhop Bowling Challenge"
CHIMPCOINS = "Letter from The Chimp: Slimy Spring Coin Challenge"
LUIGILETTR = "Letter from Luigi"
ROSALETTRL = "Letter from Rosalina: 1-up Mushrooms"
ROSALETTR1 = "Letter from Rosalina 1: Starbits"
ROSALETTR2 = "Letter from Rosalina 2: Starbits"
ROSALETTR3 = "Letter from Rosalina 3: Starbits"
ROSALETTR4 = "Letter from Rosalina 4: Starbits"
ROSALETTR5 = "Letter from Rosalina 5: Starbits"
HONEYBEELTR = "Letter from a Honeybee"
STARBUNNYLTR = "Letter from a Star Bunny"
PEACHLETTR = "Letter from Peach"

# Starbit Lumas
WORLD1SL = "Feed World 1 Starbit Luma"
WORLD2SL = "Feed World 2 Starbit Luma"
WORLD3SL = "Feed World 3 Starbit Luma"
WORLD4SL = "Feed World 4 Starbit Luma"
WORLD5SL = "Feed World 5 Starbit Luma"
WORLD6SL = "Feed World 6 Starbit Luma"
WORLD7SL = "Feed World S Starbit Luma"

# Coin Lumas
FLUFFYCL = "Feed Fluffy Bluff Coin Luma"
PUZZLECL = "Feed Puzzle Plank Coin Luma"
HIGHTACL = "Feed Hightail Falls Coin Luma"
COSMICCL = "Feed Cosmic Cove Coin Luma"
CLOUDYCL = "Feed Cloudy Court Coin Luma"
CLOCKWCL = "Feed Clockwork Ruins Coin Luma"
BATTLECL = "Feed Battle Belt Coin Luma"

# Passengers
YOSHIPASS = "Yoshi on the Ship"
YTOADPASS = "Yellow Toad on the Ship"
BTOADPASS = "Banktoad on the Ship"
MTOADPASS = "Mailtoad on the Ship"
BUNNYPASS = "Star Bunny on the Ship"
HONEYPASS = "Honeybee on the Ship"
PENGUPASS = "Penguin on the Ship"
JIBBEPASS = "Jibberjay on the Ship"
LUMA1PASS = "First Lumalee Passenger on the Ship"
LUMA2PASS = "Second Lumalee Passenger on the Ship"
WHITTPASS = "Whittle on the Ship"
GOLDGPASS = "Gold Gearmo on the Ship"
SILVGPASS = "Silver Gearmo on the Ship"
BOBOMPASS = "Bob-omb Buddy on the Ship"
GLUM1PASS = "First Green Luma on the Ship"
GLUM2PASS = "Second Green Luma on the Ship"
ROSALPASS = "Rosalina on the Ship"

# Lumalee Shop locations
SHIPLUMALEE1 = "Starship Mario First Lumalee Shop"
SHIPLUMALEE2 = "Starship Mario Second Lumalee Shop"
SPINDIGLUMALEE = "Spin-Dig Lumalee Shop"
PUZPLANLUMALEE = "Puzzle Plank Lumalee Shop"
BOULDERLUMALEE = "Boulder Bowl Lumalee Shop"
FREEZYLUMALEE = "Freezy Flake Lumalee Shop"
FEARSOMLUMALEE = "Fearsome Fleet Lumalee Shop"
FLIPSVILUMALEE = "Flipsville Lumalee Shop"
SLIPSANLUMALEE = "Slipsand Lumalee Shop"
SHIVBURLUMALEE = "Shiverburn Lumalee Shop"
BATTBELLUMALEE = "Battle Belt Lumalee Shop"
BOSSBLILUMALEE = "Boss Blitz Lumalee Shop"

# Launch Star Names
## Sky Station Galaxy
SKYOBS1HOULS = "Sky Station 1: House Launch Star"
SKYOBS1GRELS = "Sky Station 1: Green Hill Launch Star"
SKYOBS1MINLS = "Sky Station 1: Mini Planets Launch Star"
SKYOBS1MINSS = "Sky Station 1: Mini Planets Sling Star"
SKYOBS1QCOSS = "Sky Station 1: Mini Planets ?-Coin Sling Star"
SKYOBS1CYLLS = "Sky Station 1: Cylinder Launch Star"
SKYOBS1TWOLS = "Sky Station 1: Two-Sided Launch Star"
SKYOBS2HOULS = "Sky Station 2: House Launch Star"
SKYOBS2FLELS = "Sky Station 2: Sky Fleet Launch Star"
SKYOBS2FLILS = "Sky Station 2: Flipswitch Fleet Launch Star"
SKYOBS3HOULS = "Sky Station Comet: House Launch Star"
SKYOBS3CYLLS = "Sky Station Comet: Cylinder Launch Star"

## Yoshi Star Galaxy
GOODEGG1PLALS = "Yoshi Star 1: Yoshi Planet Launch Star"
GOODEGG1EARLS = "Yoshi Star 1: Earthy Planet Launch Star"
GOODEGG1TOWLS = "Yoshi Star 1: Tower Launch Star"
GOODEGG2PLALS = "Yoshi Star 2: Yoshi Planet Launch Star"
GOODEGG2MIDLS = "Yoshi Star 2: Mid-Travel Launch Star"
GOODEGG2PLTLS = "Yoshi Star 2: Planetoids Launch Star"
GOODEGG2SHOLS = "Yoshi Star 2: Shooting Gallery Launch Star"
GOODEGG2MARLS = "Yoshi Star 2: Marble Block Launch Star"

## Spin Dig Galaxy
SPINDIG1DIGLS = "Spin-Dig 1: Dig Dirt Launch Star"
SPINDIG1DRILS = "Spin-Dig 1: Drill Zone Launch Star"
SPINDIG1STELS = "Spin-Dig 1: Steel Ring Launch Star"
SPINDIG1DIRLS = "Spin-Dig 1: Dirt Tower Launch Star"
SPINDIG1REDLS = "Spin-Dig 1: Red Toadship Launch Star"
SPINDIG2TETSS = "Spin-Dig 2: Dig Dirt Sling to Vine"
SPINDIG2DARLS = "Spin-Dig 2: Dark Canister Launch Star"
SPINDIG2BLULS = "Spin-Dig 2: Blue Toadship Launch Star"

## Fluffy Bluff Galaxy
FLUFFBLUFF1WALLS = "Fluffy Bluff: Wall Jump Launch Star"
FLUFFBLUFF1WATLS = "Fluffy Bluff: Water Sphere Launch Star"
FLUFFBLUFF1LANSS = "Fluffy Bluff: Landing Big Tree Sling Star"
FLUFFBLUFF2BUISS = "Fluffy Bluff Chimp: Buildings Sling Star"

## Fiery Flotilla Galaxy
FIREFLOT1LAVLS = "Fiery Flotilla: Lava Planet Launch Star"
FIREFLOT1LANSS = "Fiery Flotilla: Fort Sling Star"

## Puzzle Plank Galaxy
PUZZPLAN1WIGLS = "Puzzle Plank: Wiggler Platform Launch Star"
PUZZPLAN1GRALS = "Puzzle Plank: Grassy Buzzsaw Launch Star"
PUZZPLAN1CHELS = "Puzzle Plank: Checkpoint Launch Star"
PUZZPLAN1SAWSS = "Puzzle Plank: Saws & Planks Sling Star"

# Boulder Bowl Galaxy
BOULBOWL1ROCLS = "Boulder Bowl: Falling Rocks Launch Star"
BOULBOWL1DODLS = "Boulder Bowl: Dodecahedron Launch Star"
BOULBOWL2ASTLS = "Boulder Bowl Comet: Asteroid Launch Star"
BOULBOWL1BOUSS = "Boulder Bowl: Boulder Sling Star"

# Hightail Fails Galaxy
HIGHTAIL1LANLS = "Hightail Falls: Hot Pepper Landing Launch Star"
HIGHTAIL1CLILS = "Hightail Falls: Hot Pepper Climb Launch Star"
HIGHTAIL1DASLS = "Hightail Falls: Hot Pepper Dash Launch Star"
HIGHTAIL2LANLS = "Hightail Falls Comet: Hot Pepper Landing Launch Star"
HIGHTAIL2CLILS = "Hightail Falls Comet: Hot Pepper Climb Launch Star"
HIGHTAIL2DASLS = "Hightail Falls Comet: Hot Pepper Dash Launch Star"

# Cosmic Cove Galaxy
COSMIC1LANSS = "Cosmic Cove 1: Landing River Sing Star"
COSMIC1CORSS = "Cosmic Cove 1: Cove Lake Coral Sling Star"
COSMIC1PILSS = "Cosmic Cove 1: Cove Lake Pillars Sling Star"
COSMIC2LANLS = "Cosmic Cove 2: Landing Launch Star"
COSMIC2TOALS = "Cosmic Cove 2: Toadship Launch Star"

# Lava Lair Galaxy
LAVALAIR1CYLLS = "Lava Lair: Lava Cylinder Launch Star"
LAVALAIR1LAVSS = "Lava Lair: Lava Sling Star"
LAVALAIR2CYLLS = "Lava Lair Comet: Lava Cylinder Launch Star"
LAVALAIR2LAVSS = "Lava Lair Comet: Lava Sling Star"

# Tall Trunk Galaxy
TALLTRUNK1BIGLS = "Tall Trunk 1: Big Tree Launch Star"
TALLTRUNK1LOGLS = "Tall Trunk 1: Carved Log Launch Star"
TALLTRUNK2BIGLS = "Tall Trunk 2: Big Tree Launch Star"

# Cloudy Court Galaxy
CLOUCOUR1CYMLS = "Cloudy Court: Cymbal Launch Star"
CLOUCOUR1TOWLS = "Cloudy Court: Tower Launch Star"
CLOUCOUR2LAULS = "Cloudy Court Comet: Launch Star"
CLOUCOUR2CS1SS = "Cloudy Court Comet: Wall Jump Sling Star"
CLOUCOUR2CS2SS = "Cloudy Court Comet: Final Sling Star"

# Haunty Halls Galaxy
HAUNHALL1HALLS = "Haunty Halls 1: Hallway Launch Star"
HAUNHALL2HALLS = "Haunty Halls 2: Hallway Launch Star"
HAUNHALL2CRESS = "Haunty Halls 2: Creepy Platforms Sling Star"

# Freezy Flake Galaxy
FREEFLAK1CABLS = "Freezy Flake 1: Log Cabin Launch Star"
FREEFLAK2CABLS = "Freezy Flake 2: Log Cabin Launch Star"
FREEFLAK2SNOLS = "Freezy Flake 2: Snowy Hill Launch Star"
FREEFLAK2WHILS = "Freezy Flake 2: Whiteout Launch Star"
FREEFLAK2SORSS = "Freezy Flake 2: Sorbetti's Head Sling Star"

# Fearsome Fleet Galaxy
FEARFLET1AIRLS = "Fearsome Fleet: Airship Launch Star"
FEARFLET1FIRSS = "Fearsome Fleet: Firing Line Sling Star"

# Supermassive Galaxy
SUPMASS1THWLS = "Supermassive: Thwomps Launch Star"
SUPMASS1KOOLS = "Supermassive: Koopa Launch Star"
SUPMASS1BLOLS = "Supermassive: ? Block Launch Star"
SUPMASS1GARLS = "Supermassive: Garden Planet Launch Star"
SUPMASS2THWLS = "Supermassive Comet: Thwomps Launch Star"
SUPMASS2KOOLS = "Supermassive Comet: Koopa Launch Star"
SUPMASS2BLOLS = "Supermassive Comet: ? Block Launch Star"
SUPMASS2GARLS = "Supermassive Comet: Garden Planet Launch Star"

# Sweet Mystery Galaxy
SWEETMYS1FLILS = "Sweet Mystery: Flipswitch Launch Star"

# Flipsville Galaxy
FLIPVILL1DOLLS = "Flipsville 1: Dollhouse Launch Star"
FLIPVILL1CHOLS = "Flipsville 1: Chomps Launch Star"
FLIPVILL1LIFLS = "Flipsville 1: Lifts Launch Star"
FLIPVILL1STALS = "Flipsville 1: Starshroom Launch Star"
FLIPVILL2DOLLS = "Flipsville 2: Dollhouse Planet Launch Star"

# Honeyhop
HONEYHOP2BASSS = "Honeyhop Chimp: Base Sling Star"
HONEYHOP2BUBSS = "Honeyhop Chimp: Cliff Pond Sling Star"

# Starshine Beach Galaxy
STARBEACH1WATLS = "Starshine Beach 1: Waterdrop Launch Star"
STARBEACH2WATLS = "Starshine Beach 2: Waterdrop Launch Star"
STARBEACH2TUNSS = "Starshine Beach 2: Water Tunnel Sling Star"

# Chompworks Galaxy
CHOMWORK1STALS = "Chompworks 1: Start Launch Star"
CHOMWORK1ROLLS = "Chompworks 1: Rolling Chomps Launch Star"
CHOMWORK1FLILS = "Chompworks 1: Flipping Platforms Launch Star"
CHOMWORK2STALS = "Chompworks 2: Start Launch Star"
CHOMWORK2ROLLS = "Chompworks 2: Rolling Chomps Launch Star"

# Gravity Gauntlet Galaxy
GRAVGAUN1FIRLS = "Gravity Gauntlet: Fire Wheel Launch Star"

# Space Storm Galaxy
SPACSTOR1PULLS = "Space Storm 1: Pull to Launch Star"
SPACSTOR1SATLS = "Space Storm 1: Satellite Launch Star"
SPACSTOR1CANLS = "Space Storm 1: Canister Launch Star"
SPACSTOR2PULLS = "Space Storm 2: Pull to Launch Star"
SPACSTOR2TOWSS = "Space Storm 2: Tower Base Sling Star"

# Boo Moon Galaxy
BOOMOON1DARLS = "Boo Moon 1: Dark Planet Launch Star"
BOOMOON1POILS = "Boo Moon 1: Poison Swamp Launch Star"
BOOMOON1MOOLS = "Boo Moon 1: Moon Launch Star"

# Slipsand Galaxy
SLIPSAND1LONLS = "Slipsand 1: Long Launch Star"
SLIPSAND1CUBLS = "Slipsand 1: Cube Launch Star"
SLIPSAND1SLILS = "Slipsand 1: Slide Launch Star"
SLIPSAND2LONLS = "Slipsand 2: Long Launch Star"

# Shiverburn Galaxy
SHIVBURN1VOLLS = "Shiverburn: Volcano Launch Star"
SHIVBURN1LAVLS = "Shiverburn: Lava Ball Launch Star"
SHIVBURN1ICELS = "Shiverburn: Lava Ice Launch Star"
SHIVBURN1GRELS = "Shiverburn: Green Toadship Launch Star"
SHIVBURN2GRELS = "Shiverburn Comet: Green Toadship Launch Star"

# Boom Bunker
BOOMBUNK1FORLS = "Boom Bunker: Fort Launch Star"
BOOMBUNK1PLALS = "Boom Bunker: Platform Launch Star"
BOOMBUNK2FORLS = "Boom Bunker Comet: Fort Launch Star"
BOOMBUNK2DARLS = "Boom Bunker Comet: Dark Matter Launch Star"

# Melty Monster Galaxy
MELTY1PULLS = "Melty Monster 1: Pull Stars Launch Star"
MELTY1MAGLS = "Melty Monster 1: Magmaargh Launch Star"
MELTY1LAVLS = "Melty Monster 1: Lava Wave Launch Star"
MELTY2ROLLS = "Melty Monster 2: Roll to Launch Star"

# Clockwork Ruins Galaxy
CLOCKWORK1COGLS = "Clockwork Ruins: Cog Wall Launch Star"
CLOCKWORK1PUSLS = "Clockwork Ruins: Push Block Launch Star"

# Flash Black Galaxy
FLASHBLACK1TOWLS = "Flash Black: Tower Launch Star"

#Throwback Galaxy
WHOMP1CANNSS = "Throwback 1: Cannon Spot Sing Star"
WHOMP2CANNSS = "Throwback 2: Cannon Spot Sing Star"
WHOMP3CANNSS = "Throwback Comet: Cannon Spot Sing Star"
# Slimy Spring Galaxy
SLIMSPRI1CAVLS = "Slimy Spring: First Cave Launch Star"
SLIMSPRI2CAVLS = "Slimy Spring Chimp: First Cave Launch Star"

# Battle Belt
BATTBELT1GOOSS = "Battle Belt: Goomba Sling Star"
BATTBELT1CINSS = "Battle Belt: Li'l Cinders Sling Star"
BATTBELT1URCSS = "Battle Belt: Urchin Sling Star"
BATTBELT1CRASS = "Battle Belt: Crabber Sling Star"
BATTBELT1PTOSS = "Battle Belt: Pink Toadship Sling Star"
BATTBELT1PUMSS = "Battle Belt: Jack O'Goomba Sling Star"
BATTBELT1RTOSS = "Battle Belt: Red Toadship Sling Star"
BATTBELT1BRRSS = "Battle Belt: Li'l Brr Sling Star"
BATTBELT1SWASS = "Battle Belt: Swaphopper Sling Star"
BATTBELT2GOOSS = "Battle Belt Comet: Goomba Sling Star"
BATTBELT2CINSS = "Battle Belt Comet: Li'l Cinders Sling Star"
BATTBELT2URCSS = "Battle Belt Comet: Urchin Sling Star"
BATTBELT2CRASS = "Battle Belt Comet: Crabber Sling Star"
BATTBELT2PTOSS = "Battle Belt Comet: Pink Toadship Sling Star"
BATTBELT2PUMSS = "Battle Belt Comet: Jack O'Goomba Sling Star"
BATTBELT2RTOSS = "Battle Belt Comet: Red Toadship Sling Star"
BATTBELT2BRRSS = "Battle Belt Comet: Li'l Brr Sling Star"
BATTBELT2SWASS = "Battle Belt Comet: Swaphopper Sling Star"

# Galaxy Generator
GALGEN1LANLS = "Galaxy Generator: Landing Launch Star"
GALGEN1LAVLS = "Galaxy Generator: Lava Cylinder Launch Star"
GALGEN1TOWLS = "Galaxy Generator: Tower Launch Star"
GALGEN2LAVLS = "Galaxy Generator Comet: Lava Cylinder Launch Star"
GALGEN2TOWLS = "Galaxy Generator Comet: Tower Launch Star"
GALGEN1DASSS = "Galaxy Generator: Dash Castle Sling Star"
GALGEN2LANSS = "Galaxy Generator Comet: Landing Sling Star"
GALGEN2DASSS = "Galaxy Generator Comet: Dash Castle Sling Star"

# Boss Blitz Galaxy
BOSSBLITZ1DINLS = "Boss Blitz: Dino Piranha Launch Star"
BOSSBLITZ1KALLS = "Boss Blitz: King Kaliente Launch Star"
BOSSBLITZ1MAJLS = "Boss Blitz: Major Burrows Launch Star"
BOSSBLITZ1BOULS = "Boss Blitz: Bouldergeist Launch Star"
BOSSBLITZ1TINLS = "Boss Blitz: Tiny Meteor Launch Star"
BOSSBLITZ2DINLS = "Boss Blitz Comet: Dino Piranha Launch Star"
BOSSBLITZ2KALLS = "Boss Blitz Comet: King Kaliente Launch Star"
BOSSBLITZ2MAJLS = "Boss Blitz Comet: Major Burrows Launch Star"
BOSSBLITZ2BOULS = "Boss Blitz Comet: Bouldergeist Launch Star"
BOSSBLITZ2TINLS = "Boss Blitz Comet: Tiny Meteor Launch Star"

# Grandmaster Galaxy
GRANDMASTER1YOSLS = "Grandmaster: Yoshi Flower Launch Star"
GRANDMASTER1SWILS = "Grandmaster: Flipswitch Launch Star"
GRANDMASTER1ELELS = "Grandmaster: Electric Clouds Launch Star"
GRANDMASTER1SWALS = "Grandmaster: Flip-Swap Launch Star"
GRANDMASTER1PULLS = "Grandmaster: Pull Star Launch Star"
GRANDMASTER2YOSLS = "Grandmaster Comet: Yoshi Flower Launch Star"
GRANDMASTER2SWILS = "Grandmaster Comet: Flipswitch Launch Star"
GRANDMASTER2ELELS = "Grandmaster Comet: Electric Clouds Launch Star"
GRANDMASTER2SWALS = "Grandmaster Comet: Flip-Swap Launch Star"
GRANDMASTER2PULLS = "Grandmaster Comet: Pull Star Launch Star"
GRANDMASTER2JUMLS = "Grandmaster Comet: Jumping Bros Launch Star"
GRANDMASTER1BROSS = "Grandmaster: Bros Landing Sling Star"
GRANDMASTER2BROSS = "Grandmaster Comet: Bros Landing Sling Star"

# Hungry Luma LS
FLUFFY1HUNGRYLS = "Fluffy Bluff: Hungry Luma Launch Star"
PUZZPL1HUNGRYLS = "Puzzle Plank: Hungry Luma Launch Star"
HIGHTA1HUNGRYLS = "Hightail Falls: Hungry Luma Launch Star"
COSMIC1HUNGRYLS = "Cosmic Cove: Hungry Luma Launch Star"
CLOUDY1HUNGRYLS = "Cloudy Court: Hungry Luma Launch Star"
CLOCKW1HUNGRYLS = "Clockwork Ruins: Hungry Luma Launch Star"
BATTLE1HUNGRYLS = "Battle Belt: Hungry Luma Launch Star"

# Pipe Names
SKYOBS1HOUPIG = "Sky Station 1: House Green Pipe"
SKYOBS1HOUPIO = "Sky Station 1: House Orange Pipe"
SKYOBS2HOUPIG = "Sky Station 2: House Green Pipe"
SKYOBS3HOUPIG = "Sky Station Comet: House Green Pipe"
SKYOBS3HOUPIO = "Sky Station Comet: House Orange Pipe"
SPIND2CAN1PIG = "Spin-Dig 2: Dark Canister 1st Green Pipe"
SPIND2CAN2PIG = "Spin-Dig 2: Dark Canister 2nd Green Pipe"
SPINDI2CANPIO = "Spin-Dig 2: Dark Canister Orange Pipe"
FLUFF1LANDPIG = "Fluffy Bluff: Landing Green Pipe"
RIGHTDOWN1LANPIG = "Rightside Down: Landing Green Pipe"
RIGHTDOWN1CORPIG = "Rightside Down: Corridor Green Pipe"
RIGHTDOWN1PIO = "Rightside Down: Orange Pipe"
PUZZPL1GRUPIG = "Puzzle Plank: Grassy Buzzsaw Green Pipe"
PUZZPLAN2PIG = "Puzzle Plank Comet: Green Pipe"
BOULBO1BOUPIG = "Boulder Bowl: Boulder Green Pipe"
COSMIC1POOPIG = "Cosmic Cove 1: Green Pipe"
COSMIC2PIG1 = "Cosmic Cove 2: Green Pipe to Cave"
COSMIC2PIG2 = "Cosmic Cove 2: Green Pipe in Cave"
COSMIC2PIG3 = "Cosmic Cove 2: Return Green Pipe"
TALLTR1LOGPIG = "Tall Trunk 1: Carved Log Green Pipe"
HAUNTY1DISPIG = "Haunty Halls 1: Green Pipe"
FREEZY1CHIPIG = "Freezy Flake 1: Snowy Hill 1 Green Pipe"
FREEZY1SLIPIG = "Freezy Flake 1: Slide Landing Green Pipe"
FREEZY2CHIPIG = "Freezy Flake 2: Snowy Hill 2 Green Pipe"
FREEZY2WHIPIG = "Freezy Flake 2: Whiteout Green Pipe"
FLIPVI2TOWPIG = "Flipsville 2: Spin-Drill Tower Pipe"
FLIPVI3TOWPIG = "Flipsville Comet : Spin-Drill Tower Pipe"
HONEYH1PONPIG = "Honeyhop: Pond Green Pipe"
STARSH1BEAPIG = "Starshine Beach 1: Tropical Beach Green Pipe"
STARSH2BEAPIG = "Starshine Beach 2: Tropical Beach Green Pipe"
CHOMPW1ROLPIG = "Chompworks 1: Bonus Room Pipe"
SPACES2TOWPIG = "Space Storm 2: Tower Green Pipe"
BOOMOON2DAPIG = "Boo Moon 2: Dark Planet Pipe"
UPDOWN1CASPIG = "Upside Dizzy: Castle Pipe"
UPDOWN1INPIG1 = "Upside Dizzy: 1st Green Pipe"
UPDOWN1BREPIO = "Upside Dizzy: Fiery Orange Pipe"
UPDOWN1INPIG2 = "Upside Dizzy: Final Green Pipe"
SLIPSA1LONPIG = "Slipsand 1: Green Pipe"
SLIPSA2LONPIG = "Slipsand 2: Green Pipe"
SLIPSA2LONPIO = "Slipsand 2: Orange Pipe"
SHIVBU1CHIPIG = "Shiverburn: Green Pipe"
MELTYM1CHIPIG = "Melty Monster 1: Green Pipe"
MELTYM2CHIPIG = "Melty Monster : Green Pipe"
CLOCKW1WHEPIG = "Clockwork Ruins: Wheel Planet Green Pipe"
CLOCKW3HAMPIG = "Clockwork Ruins Hungry Luma: Hammer Zone Green Pipe"
SLIMYS1LANPIG = "Slimy Spring: Green Pipe"
BATTLE1JACPIG = "Battle Belt: Jack O'Goomba Green Pipe"
BATTLE1SWAPIG = "Battle Belt: Swapphopper Green Pipe"
BATTLE2JACPIG = "Battle Belt Comet: Jack O'Goomba Green Pipe"
BATTLE2SWAPIG = "Battle Belt Comet: Swapphopper Green Pipe"
FLIPOU1LANPIG = "Flip-Out: Green Pipe"
FLIPOU2LANPIG = "Flip-Out Comet: Green Pipe"
SHIP2EARPIPE = "Starship Mario: Left Ear Pipe"

# Special Locations
VISITWORLD1 = "Visit World 1"
VISITWORLD2 = "Visit World 2"
VISITWORLD3 = "Visit World 3"
VISITWORLD4 = "Visit World 4"
VISITWORLD5 = "Visit World 5"
VISITWORLD6 = "Visit World 6"
VISITWORLD7 = "Visit World 7"
SPEAKTOLUBB = "Speak to Lubba: You're the Captain Now!"
OPENWORLDMP = "Open the World Map"

# Dice Blocks
SHIPABOVEGDIE = "Starship Mario: Aboveground Chance Cube"
LUMA1CHANCDIE = "Starship Mario: First Lumalee Chance Cube"
LUMA2CHANDIE1 = "Starship Mario: Second Lumalee Chance Cube #1"
LUMA2CHANDIE2 = "Starship Mario: Second Lumalee Chance Cube #2"
LUMA2CHANDIE3 = "Starship Mario: Second Lumalee Chance Cube #3"
LUMA2CHANDIE4 = "Starship Mario: Second Lumalee Chance Cube #4"
LUMA2CHANDIE5 = "Starship Mario: Second Lumalee Chance Cube #5"
YOSHIS1DIRDIE = "Yoshi Star 1: Dirt Planet Chance Cube"
BOULDE1BODIE1 = "Boulder Bowl: Bonus Room Chance Cube #1"
BOULDE1BODIE2 = "Boulder Bowl: Bonus Room Chance Cube #2"
BOULDE1BODIE3 = "Boulder Bowl: Bonus Room Chance Cube #3"
BOULDE1BODIE4 = "Boulder Bowl: Bonus Room Chance Cube #4"
BOULDE1BODIE5 = "Boulder Bowl: Bonus Room Chance Cube #5"
BOULDE1BODIE6 = "Boulder Bowl: Bonus Room Chance Cube #6"
TALLTR1BODIE1 = "Tall Trunk 1: Bonus Room Chance Cube #1"
TALLTR1BODIE2 = "Tall Trunk 1: Bonus Room Chance Cube #2"
TALLTR1BODIE3 = "Tall Trunk 1: Bonus Room Chance Cube #3"
FREFLASNOWDIE = "Freezy Flake: Snowy Hill Chance Cube"
FREFLA2BODIE1 = "Freezy Flake 2: Bonus Room Chance Cube #1"
FREFLA2BODIE2 = "Freezy Flake 2: Bonus Room Chance Cube #2"
FREFLA2BODIE3 = "Freezy Flake 2: Bonus Room Chance Cube #3"
CHOMPW1BODIE1 = "Chompworks 1: Bonus Room Chance Cube #1"
CHOMPW1BODIE2 = "Chompworks 1: Bonus Room Chance Cube #2"
CHOMPW1BODIE3 = "Chompworks 1: Bonus Room Chance Cube #3"
HONEYH1BODIE1 = "Honeyhop 1: Bonus Room Chance Cube #1"
HONEYH1BODIE2 = "Honeyhop 1: Bonus Room Chance Cube #2"
HONEYH1BODIE3 = "Honeyhop 1: Bonus Room Chance Cube #3"
BOOMBUSTRTDIE = "Boom Bunker: Start Chance Cube"
THROWBASRTDIE = "Throwback: Starting Area Chance Cube"

# 1-up locations
SHIPTOADS1UP = "Starship Mario: Starshroom 1-Up"
SHIPTENFR1UP = "Starship Mario: Ten Fruit 1-Up"
SHIPCLOUD1UP = "Starship Mario: Cloud 1-Up"
SKST1PIOR1UP = "Sky Station 1: Orange Pipe 1-Up"
SKST1YELL1UP = "Sky Station 1: Yellow Platform 1-Up"
SKST1NOT1UP1 = "Sky Station 1: Notes 1-Up #1"
SKST1NOT1UP2 = "Sky Station 1: Notes 1-Up #2"
SKST1NOT1UP3 = "Sky Station 1: Notes 1-Up #3"
SKST1BON1UP1 = "Sky Station 1: Teleporter 1-Up #1"
SKST1BON1UP2 = "Sky Station 1: Teleporter 1-Up #2"
SKST1BON1UP3 = "Sky Station 1: Teleporter 1-Up #3"
SKST1CART1UP = "Sky Station 1: Rotating Cart 1-Up"
SKST1CRYS1UP = "Sky Station 1: Crystal 1-Up Between Rotating Carts"
SKST1STAI1UP = "Sky Station 1: 1-Up Behind Octoomba Stairs"
SKST2CHES1UP = "Sky Station 2: First Planet Chest 1-Up"
SKST2CHEK1UP = "Sky Station 2: 1-Up Above Checkpoint Flag"
SKST2BON1UP1 = "Sky Station 2: Teleporter 1-Up #1"
SKST2BON1UP2 = "Sky Station 2: Teleporter 1-Up #2"
SKST2BON1UP3 = "Sky Station 2: Teleporter 1-Up #3"
SKST2WOOD1UP = "Sky Station 2: Wooden Alcove 1-Up"
SKST2FLIP1UP = "Sky Station 2: Flipswitches 1-Up"
YOSH1RIGH1UP = "Yoshi Star 1: Right Ledge 1-Up"
YOSH1FRUI1UP = "Yoshi Star 1: Ten Fruit 1-Up"
YOSH1BON1UP1 = "Yoshi Star 1: Teleporter 1-Up #1"
YOSH1BON1UP2 = "Yoshi Star 1: Teleporter 1-Up #2"
YOSH1BON1UP3 = "Yoshi Star 1: Teleporter 1-Up #3"
YOSH1WOOD1UP = "Yoshi Star 1: Wooden Ledge 1-Up"
YOSH2BON1UP1 = "Yoshi Star 2: Teleporter 1-Up #1"
YOSH2BON1UP2 = "Yoshi Star 2: Teleporter 1-Up #2"
YOSH2BON1UP3 = "Yoshi Star 2: Teleporter 1-Up #3"
YOSH2CAGE1UP = "Yoshi Star 2: Caged 1-Up"
YOSH2SECR1UP = "Yoshi Star 2: Secret Island 1-Up Beneath Platform"
YOSH2WOOD1UP = "Yoshi Star 2: Wooden Ledge 1-Up"
YOSH2STON1UP = "Yoshi Star 2: 1-Up on Top of Marble Block Planet"
SPIN1CAGE1UP = "Spin-Dig 1: Starting Planet Caged 1-Up"
SPIN1BON1UP1 = "Spin-Dig 1: Teleporter 1-Up #1"
SPIN1BON1UP2 = "Spin-Dig 1: Teleporter 1-Up #2"
SPIN1BON1UP3 = "Spin-Dig 1: Teleporter 1-Up #3"
SPIN1YELL1UP = "Spin-Dig 1: Yellow Platform 1-Up"
SPIN2BON1UP1 = "Spin-Dig 2: Teleporter 1-Up #1"
SPIN2BON1UP2 = "Spin-Dig 2: Teleporter 1-Up #2"
SPIN2BON1UP3 = "Spin-Dig 2: Teleporter 1-Up #3"
FLUF1BRID1UP = "Fluffy Buff: 1-Up Beneath Bridge"
FLUF1ROOC1UP = "Fluffy Buff: Bonus Room ? Coin 1-Up Reward"
FLUF1CLOC1UP = "Fluffy Buff: Cloud ? Coin 1-Up Reward"
FLUF1BOMP1UP = "Fluffy Buff: 1-Up Above Bomp"
FLUF2BRID1UP = "Fluffy Buff Ch: 1-Up Beneath Bridge"
FLUF1CLOU1UP = "Fluffy Buff: 1-Up On Cloud Left of Chimp"
FLUF2TREE1UP = "Fluffy Buff Ch: 1-Up On Large Tree Top"
FLUF2CLIF1UP = "Fluffy Buff Ch: 1-Up Above Tree on Top Cliff"
FLUF3PLAT1UP = "Fluffy Buff S: 1-Up on Rotating Platform"
FLUF3BEH1UP1 = "Fluffy Buff S: 1-Up Behind Castle #1"
FLUF3BEH1UP2 = "Fluffy Buff S: 1-Up Behind Castle #2"
FLIPFENCE1UP = "Flip-Swap: Electric Fences 1-Up"
FLIPCHOMP1UP = "Flip-Swap: Chomps 1-Up"
FLIPPURPL1UP = "Flip-Swap P: 1-Up"
RIGHTBON1UP1 = "Rightside Down: Teleporter 1-Up #1"
RIGHTBON1UP2 = "Rightside Down: Teleporter 1-Up #2"
RIGHTBON1UP3 = "Rightside Down: Teleporter 1-Up #3"
RIGHTELEV1UP = "Rightside Down: 1-Up Above Elevator"
RIGHTFIN1UP1 = "Rightside Down: Final Planet Corner 1-Up #1"
RIGHTFIN1UP2 = "Rightside Down: Final Planet Corner 1-Up #2"
RIGHTFIN1UP3 = "Rightside Down: Final Planet Corner 1-Up #3"
RIGHTFIN1UP4 = "Rightside Down: Final Planet Corner 1-Up #4"
RIGHTSTAR1UP = "Rightside Down: 1-Up Near Star"
RIGHTCRAT1UP = "Rightside Down: S Bottom Left Crate 1-Up"
FIERYWALL1UP = "Fiery Flotilla: 1-Up on Castle Wall"
PUZZLNOT1UP1 = "Puzzle Plank: Notes 1-Up #1"
PUZZLNOT1UP2 = "Puzzle Plank: Notes 1-Up #2"
PUZZLNOT1UP3 = "Puzzle Plank: Notes 1-Up #3"
PUZZLCOIN1UP = "Puzzle Plank: Bonus Room ? Coin 1-Up Reward"
PUZZLSAWB1UP = "Puzzle Plank: 1-Up on Saw Planks"
HIGH1PENG1UP = "Hightail Falls: Penguru 1-Up"
HIGH1BON1UP1 = "Hightail Falls: Teleporter 1-Up #1"
HIGH1BON1UP2 = "Hightail Falls: Teleporter 1-Up #2"
HIGH1BON1UP3 = "Hightail Falls: Teleporter 1-Up #3"
HIGH1STAR1UP = "Hightail Falls: 1-Up Above Star"
HIGH2PURP1UP = "Hightail Falls C: Purple Block Wall 1-Up"
BOUL1COME1UP = "Boulder Bowl: 1-Up Behind Comet Medal"
BOUL2STRT1UP = "Boulder Bowl C: 1-Up Beneath Starting Planet"
BOUL2BLU1UP1 = "Boulder Bowl C: Blue Crabber 1-Up #1"
BOUL2BLU1UP2 = "Boulder Bowl C: Blue Crabber 1-Up #2"
BOUL2BLU1UP3 = "Boulder Bowl C: Blue Crabber 1-Up #3"
COSM1JELL1UP = "Cosmic Cove 1: Crate Near Jellyfish 1-Up"
COSM2MINE1UP = "Cosmic Cove 2: 1-Up by Mine"
COSM2FINA1UP = "Cosmic Cove 2: Final Planet Underground 1-Up"
WILDGLIDE1UP = "Wild Glide: 1-Up"
HONEYCOIN1UP = "Honeybloom: ? Coin 1-Up Reward"
LAVA1MOVE1UP = "Lava Lair: Moving Platforms 1-Up"
LAVA1FLOM1UP = "Lava Lair: Left Flomp 1-Up"
LAVA1COIN1UP = "Lava Lair: ? Coin 1-Up Reward"
LAVA1MATR1UP = "Lava Lair: Mattermouths 1-Up"
LAVA2WHOM1UP = "Lava Lair C: 1-Up Above Whomps"
LAVA2STAR1UP = "Lava Lair C: 1-Up Behind the Star"
TALL1CRYS1UP = "Tall Trunk: First Planet Crystal 1-Up"
TALL1BON1UP1 = "Tall Trunk 1: Teleporter 1-Up #1"
TALL1BON1UP2 = "Tall Trunk 1: Teleporter 1-Up #2"
TALL1BON1UP3 = "Tall Trunk 1: Teleporter 1-Up #3"
TALL1CHEK1UP = "Tall Trunk 1: 1-Up Below First Checkpoint"
TALL1COIN1UP = "Tall Trunk 1: ? Coin 1-Up Reward"
TALL2BON1UP1 = "Tall Trunk 2: Teleporter 1-Up #1"
TALL2BON1UP2 = "Tall Trunk 2: Teleporter 1-Up #2"
TALL2BON1UP3 = "Tall Trunk 2: Teleporter 1-Up #3"
TALL2SPIK1UP = "Tall Trunk 2: Slide 1-Up Beteween Spikes"
TALL2GAPP1UP = "Tall Trunk 2: Slide 1-Up After Gap"
TALL2STAR1UP = "Tall Trunk 2: Star Area 1-Up"
CLOU1DINO1UP = "Cloudy Court 1: 1-Up Beneath Dino Hedge"
CLOU1COIN1UP = "Cloudy Court 1: ? Coin 1-Up Reward"
CLOU1BON1UP1 = "Cloudy Court 1: Teleporter 1-Up #1"
CLOU1BON1UP2 = "Cloudy Court 1: Teleporter 1-Up #2"
CLOU1BON1UP3 = "Cloudy Court 1: Teleporter 1-Up #3"
CLOU1DOME1UP = "Cloudy Court 1: Grassy Dome 1-Up"
CLOU1LEF1UP1 = "Cloudy Court 2: 2D Left Platform 1-Up #1"
CLOU1LEF1UP2 = "Cloudy Court 2: 2D Left Platform 1-Up #2"
CLOU1LEF1UP3 = "Cloudy Court 2: 2D Left Platform 1-Up #3"
HAUN1BON1UP1 = "Haunty Halls 1: Teleporter 1-Up #1"
HAUN1BON1UP2 = "Haunty Halls 1: Teleporter 1-Up #2"
HAUN1BON1UP3 = "Haunty Halls 1: Teleporter 1-Up #3"
HAUN1CARP1UP = "Haunty Halls 1: Long Carpet Platform 1-Up"
HAUN1BULB1UP = "Haunty Halls 1: Bulb Berry 1-Up"
HAUN2BON1UP1 = "Haunty Halls 2: Teleporter 1-Up #1"
HAUN2BON1UP2 = "Haunty Halls 2: Teleporter 1-Up #2"
HAUN2BON1UP3 = "Haunty Halls 2: Teleporter 1-Up #3"
FREZ1HILL1UP = "Freezy Flake 1:-Up on Snowy Hill"
FREZ1TREE1UP = "Freezy Flake 1: 1-Up in Snow Tree"
FREZ2STR1UP1 = "Freezy Flake 2: Snowstorm Star Platform 1-Up #1"
FREZ2STR1UP2 = "Freezy Flake 2: Snowstorm Star Platform 1-Up #2"
FREZ2STR1UP3 = "Freezy Flake 2: Snowstorm Star Platform 1-Up #3"
RMAS1BRUS1UP = "Rolling Masterpiece: Paintbrush Planet 1-Up"
RMAS1JUNK1UP = "Rolling Masterpiece: Space Junk 1-Up"
RMAS1NOT1UP1 = "Rolling Masterpiece: Wooden Planet Notes 1-Up #1"
RMAS1NOT1UP2 = "Rolling Masterpiece: Wooden Planet Notes 1-Up #2"
RMAS1NOT1UP3 = "Rolling Masterpiece: Wooden Planet Notes 1-Up #3"
RMAS2GRS1UP1 = "Rolling Masterpiece C: Grassy Planet Notes 1-Up #1"
RMAS2GRS1UP2 = "Rolling Masterpiece C: Grassy Planet Notes 1-Up #2"
RMAS2GRS1UP3 = "Rolling Masterpiece C: Grassy Planet Notes 1-Up #3"
BEAT1PATH1UP = "Beat Block: 1-Up on Main Path"
BEAT1CRYS1UP = "Beat Block: Crystal 1-Up"
BEAT2PYRA1UP = "Beat Block C: 1-Up Behind Block Pyramid"
FEAR1ELEC1UP = "Fearsome Fleet: Bowser Jr. Statue Near Electricity 1-Up"
SUPE1LONG1UP = "Supermassive 1: Long Jump Tutorial 1-Up"
SUPE1THWO1UP = "Supermassive 1: 1-Up Atop Thwomp"
SUPE1COIN1UP = "Supermassive 1: Brick Block ? Coin 1-Up Reward"
SUPE1WIGG1UP = "Supermassive 1: Big Wigglers 1-Up"
SUPE1FLAG1UP = "Supermassive 1: Above Flagpole ? Coin 1-Up Reward"
SUPE2LONG1UP = "Supermassive 2: Long Jump Tutorial 1-Up"
SUPE2THWO1UP = "Supermassive 2: 1-Up Atop Thwomp"
SUPE2COIN1UP = "Supermassive 2: Brick Block ? Coin 1-Up Reward"
SUPE2WIGG1UP = "Supermassive 2: Big Wigglers 1-Up"
SUPE2FLAG1UP = "Supermassive 2: Above Flagpole ? Coin 1-Up Reward"
FLIP1BON1UP1 = "Flipsville 1: Teleporter 1-Up #1"
FLIP1BON1UP2 = "Flipsville 1: Teleporter 1-Up #2"
FLIP1BON1UP3 = "Flipsville 1: Teleporter 1-Up #3"
FLIP1CRAT1UP = "Flipsville 1: Corner Crate 1-Up"
FLIP2LAUN1UP = "Flipsville 2: 1-Up Below Launch Star"
FLIP2COIN1UP = "Flipsville 2: Silver Stars ? Coin 1-Up Reward"
FLIP2STAR1UP = "Flipsville 2: Silver Stars 1-Up on Right"
FLIP2BON1UP1 = "Flipsville 2: Teleporter 1-Up #1"
FLIP2BON1UP2 = "Flipsville 2: Teleporter 1-Up #2"
FLIP2BON1UP3 = "Flipsville 2: Teleporter 1-Up #3"
STSH1ROOF1UP = "Starshine Beach 1: 1-Up on Hut Roof"
STSH1COIN1UP = "Starshine Beach 1: Bonus Room ? Coin 1-Up Reward"
STSH1BON1UP1 = "Starshine Beach 1: Teleporter 1-Up #1"
STSH1BON1UP2 = "Starshine Beach 1: Teleporter 1-Up #2"
STSH1BON1UP3 = "Starshine Beach 1: Teleporter 1-Up #3"
STSH1BLIM1UP = "Starshine Beach 1: 1-Up High Above Blimp Fruit"
STSH1OCEA1UP = "Starshine Beach 1: 1-Up At Bottom of Ocean"
STSH2ROOF1UP = "Starshine Beach 2: 1-Up on Hut Roof"
STSH2COIN1UP = "Starshine Beach 2: Bonus Room ? Coin 1-Up Reward"
STSH2CHUK1UP = "Starshine Beach 2: Yellow Chuckster 1-Up"
STSH2SPRI1UP = "Starshine Beach 2: 1-Up Above Ocean Spring Platform"
STSH2GRIN1UP = "Starshine Beach 2: 1-Up Between Gringills"
STSH2BON1UP1 = "Starshine Beach 2: Teleporter 1-Up #1"
STSH2BON1UP2 = "Starshine Beach 2: Teleporter 1-Up #2"
STSH2BON1UP3 = "Starshine Beach 2: Teleporter 1-Up #3"
CHOM1CHBL1UP = "Chompworks 1: 1-Up Below Start Chomp Dispenser"
CHOM1CHUP1UP = "Chompworks 1: 1-Up Atop Mini Chomp Dispenser"
CHOM1TILT1UP = "Chompworks 1: 1-Up Above Tilting Platform"
CHOM2CHBL1UP = "Chompworks 2: 1-Up Below Start Chomp Dispenser"
CHOM2CHEK1UP = "Chompworks 2: 1-Up High Above Checkpoint"
CHOM2COIN1UP = "Chompworks 2: Tower ? Coin 1-Up Reward"
CHOM2SPIN1UP = "Chompworks 2: Tower 1-Up on Spinning Bar"
SWEETPATH1UP = "Sweet Mystery: Second Path 1-Up"
SWEETSHRK1UP = "Sweet Mystery: Shrinking Platform 1-Up"
HONEYWATR1UP = "Honeyhop 1: Hidden 1-Up in Water"
GRAVIWATR1UP = "Gravity Gauntlet: Underwater 1-Up"
GRAVICOIN1UP = "Gravity Gauntlet: Underwater ? Coin 1-Up Reward"
GRAVICHEK1UP = "Gravity Gauntlet: 1-Up High Above Checkpoint"
GRAVIWHOM1UP = "Gravity Gauntlet: 1-Up Among Whomps"
GRAVIGATE1UP = "Gravity Gauntlet: 1-Up Behind Grate"
SPAC1TOPM1UP = "Space Storm 1: Topman Planet Caged 1-Up"
SPAC2BONU1UP = "Space Storm 2: Bonus Room 1-Up Reward"
SAND1BONU1UP = "Slipsand 1: Bonus Room 1-Up Reward"
SAND1TORC1UP = "Slipsand 1: Torch 1-Up"
SAND2TUB1UP1 = "Slipsand 2: Sand Tube End 1-Up #1"
SAND2TUB1UP2 = "Slipsand 2: Sand Tube End 1-Up #2"
SAND2TUB1UP3 = "Slipsand 2: Sand Tube End 1-Up #3"
SAND2SSEA1UP = "Slipsand 2: Sandy Sea 1-Up"
SHIVEVOLC1UP = "Shiverburn: Volcano Planet 1-Up Mushroom"
SHIVECHES1UP = "Shiverburn: Spinning Stones Chest 1-Up"
SHIVESTON1UP = "Shiverburn: Spinning Stones Far Side 1-Up"
SHIVEMETE1UP = "Shiverburn: Meteor Rain Cloud 1-Up"
SHIVEICIC1UP = "Shiverburn: Icicle Rain 1-Up"
MOON1BON1UP1 = "Boo Moon 1: Teleporter 1-Up #1"
MOON1BON1UP2 = "Boo Moon 1: Teleporter 1-Up #2"
MOON1BON1UP3 = "Boo Moon 1: Teleporter 1-Up #3"
MOON1NOT1UP1 = "Boo Moon 1: Snake Block Notes 1-Up #1"
MOON1NOT1UP2 = "Boo Moon 1: Snake Block Notes 1-Up #2"
MOON1NOT1UP3 = "Boo Moon 1: Snake Block Notes 1-Up #3"
MOON1BOOK1UP = "Boo Moon 1: Pop-Up Book 1-Up"
MOON2BON1UP1 = "Boo Moon 2: Teleporter 1-Up #1"
MOON2BON1UP2 = "Boo Moon 2: Teleporter 1-Up #2"
MOON2BON1UP3 = "Boo Moon 2: Teleporter 1-Up #3"
MOON2CRY1UP1 = "Boo Moon 2: Starting Planet Crystal 1-Up #1"
MOON2CRY1UP2 = "Boo Moon 2: Starting Planet Crystal 1-Up #2"
MOON2WIND1UP = "Boo Moon 2: Windy Hallway 1-Up"
UPSIDPIPE1UP = "Upside Dizzy: 1-Up Next to Secret Pipe"
FLEETWALL1UP = "Fleet Glide: Third Wall 1-Up"
FLEETGATE1UP = "Fleet Glide: 1-Up Before Second Comet Gate"
BOOM1BULL1UP = "Boom Bunker: Start Cannon Bullseye 1-Up"
BOOM1PLAT1UP = "Boom Bunker: Spinning Platforms Bullseye 1-Up"
BOOM2BULL1UP = "Boom Bunker C: Dark Matter Bullseye 1-Up"
BOOM2BOSS1UP = "Boom Bunker C: 1-Up Before Boss"
MELT2BOWL1UP = "Melty Monster 2: 1-Up"
CLOC1PUSH1UP = "Clockwork Ruins: Pusher Walls 1-Up"
CLOC1DRAL1UP = "Clockwork Ruins: Rolling Drums Alcove 1-Up"
CLOC1STON1UP = "Clockwork Ruins: 1-Up Outside Spinning Stones"
CLOC1BONU1UP = "Clockwork Ruins: Bonus Room 1-Up Reward"
CLOC1DRUM1UP = "Clockwork Ruins: Upper Rolling Drums Hill 1-Up"
CLOC3HAMM1UP = "Clockwork Ruins S: 1-Up on Hammer"
CLOC3LEDG1UP = "Clockwork Ruins S: 1-Up on Top Ledge"
THROW1BON1UP1 = "Throwback 1: Teleporter 1-Up #1"
THROW1BON1UP2 = "Throwback 1: Teleporter 1-Up #2"
THROW1BON1UP3 = "Throwback 1: Teleporter 1-Up #3"
THROW1NOT1UP1 = "Throwback 1: Slope Behind Mountain Crate Notes 1-Up #1"
THROW1NOT1UP2 = "Throwback 1: Slope Behind Mountain Crate Notes 1-Up #2"
THROW1NOT1UP3 = "Throwback 1: Slope Behind Mountain Crate Notes 1-Up #3"
THROW1THWO1UP = "Throwback 1: 1-Up on Top of Thwomp"
THROW1FLAG1UP = "Throwback 1: 1-Up on Flagpole"
THROW2NOT1UP1 = "Throwback 2: Slope Behind Mountain Crate Notes 1-Up #1"
THROW2NOT1UP2 = "Throwback 2: Slope Behind Mountain Crate Notes 1-Up #2"
THROW2NOT1UP3 = "Throwback 2: Slope Behind Mountain Crate Notes 1-Up #3"
THROW2THWO1UP = "Throwback 1: 1-Up on Top of Thwomp"
THROW2FLAG1UP = "Throwback 1: 1-Up on Flagpole"
THROW2BON1UP1 = "Throwback 2: Teleporter 1-Up #1"
THROW2BON1UP2 = "Throwback 2: Teleporter 1-Up #2"
THROW2BON1UP3 = "Throwback 2: Teleporter 1-Up #3"
BATTLBLUE1UP = "Battle Belt: Blue Crabber 1-Up"
BATTLLAVA1UP = "Battle Belt C: 1-Up Over Lava Pool"
FLASHLEDG1UP = "Flash Black: Overhang 1-Up"
FLASHPLAT1UP = "Flash Black: Final Area Crystal 1-Up"
SLIMYLCHE1UP = "Slimy Spring: Bonus Room Bottom Left Chest 1-Up"
SLIMYMCHE1UP = "Slimy Spring: Bonus Room Middle Chest 1-Up"
SLIMYTCHE1UP = "Slimy Spring: Bonus Room Top Right Chest 1-Up"
SLIMYLAUN1UP = "Slimy Spring: 1-Up Below Launch Star"
SLIMYCHEK1UP = "Slimy Spring: 1-Up by Checkpoint"
GALA1DRIL1UP = "Galaxy Generator: Spin-Drill Section 1-Up"
GALA1CLOU1UP = "Galaxy Generator: Cloud Flower Section Secret Path 1-Up"
GALA1YOSH1UP = "Galaxy Generator: Yoshi Section Flowers 1-Up"
GALA2MEDA1UP = "Galaxy Generator C: Comet Medal 1-Up"
MARIOFLOT1UP = "Mario Squared: 1-Up"
RCOSTLEFT1UP = "Rolling Coaster: Left Path 1-Up"
RCOSTRIGT1UP = "Rolling Coaster: Right Path 1-Up"
RCOST2RIGT1UP = "Rolling Coaster C: Right Path 1-Up"
TWST1PLAK1UP = "Twisty Trials: 1-Up Between Planks"
TWST1GEAR1UP = "Twisty Trials: 1-Up on Block Near Gears"
TWST2STRT1UP = "Twisty Trials C: 1-Up on Block Near Start"
TWST2CHEK1UP = "Twisty Trials C: 1-Up on Block Before Checkpoint"
TWST2GEAR1UP = "Twisty Trials C: 1-Up on Block Past Gears"
TWST2OEND1UP = "Twisty Trials C: 1-Up on Block Near Old End"
TWST2FIN1UP1 = "Twisty Trials C: 1-Up on Block in New Area #1"
TWST2FIN1UP2 = "Twisty Trials C: 1-Up on Block in New Area #2"
STON1SPIN1UP = "Stone Cyclone: 1-Up After Spinning Platforms"
STON1SHRK1UP = "Stone Cyclone: Shrinking Platforms 1-Up"
STON2SLID1UP = "Stone Cyclone C: 1-Up on Sliding Stone Blocks"
STON2TOYB1UP = "Stone Cyclone C: 1-Up on Tox Box Path"
FLIP1STRT1UP = "Flip-Out: 1-Up Above Start"
FLIP1FINA1UP = "Flip-Out: Final Section 1-Up"
FLIP2COME1UP = "Flip-Out C: Comet Medal 1-Up"
GRND1CLOU1UP = "Grandmaster: 1-Up Above Cloud Checkpoint"
GRND2CLOU1UP = "Grandmaster: 1-Up Above Cloud Checkpoint"
GRND2COME1UP = "Grandmaster C: Comet Medal 1-Up"
GRND2GATE1UP = "Grandmaster C: 1-Up Behind Gate"
# Bonus Teleporter Clears
SKYSTA1BONUSCL = "Sky Station 1: Bonus Teleporter Clear"
SKYSTA2BONUSCL = "Sky Station 2: Bonus Teleporter Clear"
YOSHIS1BONUSCL = "Yoshi Star 1: Bonus Teleporter Clear"
YOSHIS2BONUSCL = "Yoshi Star 2: Bonus Teleporter Clear"
SPINDI1BONUSCL = "Spin-Dig 1: Bonus Teleporter Clear"
SPINDI2BONUSCL = "Spin-Dig 2: Bonus Teleporter Clear"
RIGHTSIBONUSCL = "Rightside Down: Bonus Teleporter Clear"
HIGHTA1BONUSCL = "Hightail Falls 1: Bonus Teleporter Clear"
TALLTR1BONUSCL = "Tall Trunk 1: Bonus Teleporter Clear"
TALLTR2BONUSCL = "Tall Trunk 2: Bonus Teleporter Clear"
CLOUDY1BONUSCL = "Cloudy Court 1: Bonus Teleporter Clear"
HAUNTY1BONUSCL = "Haunty Halls 1: Bonus Teleporter Clear"
HAUNTY2BONUSCL = "Haunty Halls 2: Bonus Teleporter Clear"
FLIPSV1BONUSCL = "Flipsville 1: Bonus Teleporter Clear"
FLIPSV2BONUSCL = "Flipsville 2: Bonus Teleporter Clear"
STARSH1BONUSCL = "Starshine Beach 1: Bonus Teleporter Clear"
STARSH2BONUSCL = "Starshine Beach 2: Bonus Teleporter Clear"
BOOMOO1BONUSCL = "Boo Moon 1: Bonus Teleporter Clear"
BOOMOO2BONUSCL = "Boo Moon 2: Bonus Teleporter Clear"
THROWB1BONUSCL = "Throwback 1: Bonus Teleporter Clear"
THROWB2BONUSCL = "Throwback 2: Bonus Teleporter Clear"

# First Power-Up locations
SUPASTAR1ST    = "Rainbow Star"
FIREFLOWER1ST  = "Fire Flower"
BEEMARIO1ST    = "Bee Mushroom"
SPRING1ST      = "Spring Mushroom"
BOOMARIO1ST    = "Boo Mushroom"
CLOUD1ST       = "Cloud Mushroom"
ROCK1ST        = "Rock Mushroom"
SPINDRILL1ST   = "Spin Drill"