# Origin Region
SHIP = "Starship Mario"

# Hub Regions
WORLD1 = "World 1"
WORLD2 = "World 2"
WORLD6 = "World 6"
WORLD5 = "World 5"
WORLD4 = "World 4"
WORLD3 = "World 3"
WORLD7 = "World S"
SHIPINSIDE = "Inside Starship Mario"

# Hungry Luma Galaxies - 7
FLIPSWAP = "Flip Swap Galaxy"
HONEYBLOOM = "Honeybloom Galaxy"
BEATBLOCK = "Beat Block Galaxy"
SWEETMYS = "Sweet Mystery Galaxy"
FLEETGLIDE = "Fleet Glide Galaxy"
FLASHBLACK = "Flash Black Galaxy"
FLIPOUT = "Flip-Out Galaxy"

# World S Galaxies - 5
MARIO = "Mario Squared Galaxy"
ROLLCOAST = "Rolling Coaster Galaxy"
TWISTTRI = "Twisty Trials Galaxy"
STONECYC = "Stone Cyclone Galaxy"
GRANDMASTER = "Grandmaster Galaxy"

# Boss Galaxies - 6 + goal
BOWJR1 = "Bowser Jr.'s Fiery Flotilla"
BOWJR2 = "Bowser Jr.'s Fearsome Fleet"
BOWJR3 = "Bowser Jr.'s Boom Bunker"
BOWSER1 = "Bowser's Lava Lair"
BOWSER2 = "Bowser's Gravity Gauntlet"
BOWSER3 = "Bowser's Galaxy Generator"
BOSSBLITZ = "Boss Blitz Galaxy"

# Major Galaxies - 24
SKYOBS = "Sky Station Galaxy"
GOODEGG = "Yoshi Star Galaxy"
SPINDIG = "Spin-Dig Galaxy"
FLUFFBLUFF = "Fluffy Bluff Galaxy"
PUZZPLAN = "Puzzle Plank Galaxy"
HIGHTAIL = "Hightail Falls Galaxy"
BOULBOWL = "Boulder Bowl Galaxy"
COSMICO = "Cosmic Cove Galaxy"
TALLTRUNK = "Tall Trunk Galaxy"
CLOUCOUR = "Cloudy Court Galaxy"
HAUNHALL = "Haunty Halls Galaxy"
FREEFLAKE = "Freezy Flake Galaxy"
SUPMASS = "Supermassive Galaxy"
FLIPVILL = "Flipsville Galaxy"
STARBEACH = "Starshine Beach Galaxy"
CHOMWORK = "Chompworks Galaxy"
SPACSTOR = "Space Storm Galaxy"
SLIPSAND = "Slipsand Galaxy"
SHIVBURN = "Shiverburn Galaxy"
BOOMOON = "Boo Moon Galaxy"
MELTY = "Melty Monster Galaxy"
CLOCKWORK = "Clockwork Ruins Galaxy"
WHOMPFORT = "Throwback Galaxy"
BATTLEBELT = "Battle Belt Galaxy"

# Minor Galaxies - 6
RIGHTDOWN = "Rightside Down Galaxy"
WILDGLIDE = "Wild Glide Galaxy"
ROLLMAST = "Rolling Masterpiece Galaxy"
HONEYHOP = "Honeyhop Galaxy"
UPDOWN = "Upside Dizzy Galaxy"
SLIMSPRI = "Slimy Spring Galaxy"

# Planetoid Subregions
SKYOBS1STARTTOPSIDE = "Sky Station 1: Starting Planet Topside"
SKYOBS2STARTTOPSIDE = "Sky Station 2: Starting Planet Topside"
SKYOBS1STARTBOTTOM = "Sky Station 1: Starting Planet Bottom"
SKYOBS2STARTBOTTOM = "Sky Station 2: Starting Planet Bottom"
SKYOBS1TOPOFHOUSE = "Sky Station 1: Top of House"
SKYOBS2TOPOFHOUSE = "Sky Station 2: Top of House"
SKYOBS1GREENHILL = "Sky Station 1: Green Hill Planet"
SKYOBS1OCTOBONUS = "Sky Station 1: Octo Bonus Arena"
SKYOBS2OCTOBONUS = "Sky Station 2: Octo Bonus Arena"
SKYOBS1MINIPLANETS = "Sky Station 1: Mini Planets"
SKYOBS1CYLINDER = "Sky Station 1: Cylindrical Planet"
SKYOBS1BEFOREBOSS = "Sky Station 1: Two-Sided Planet"
SKYOBS1BOSS = "Sky Station 1: Peewee Piranha Planet"
SKYOBS2SKYFLEET = "Sky Station 2: Sky Fleet Cylinder"
SKYOBS2FLIPSWITCH = "Sky Station 2: Flipswitch Fleet"
SKYOBS2GRASSFLEET = "Sky Station 2: Grassy Fleet Ship"
SKYOBS1GSTAR1 = "Sky Station 1: Green Star 1 Region"


TALLTRUNK1BIGTREE = "Tall Trunk 1: Big Tree Planet"
TALLTRUNK1PIRANHABONUS = "Tall Trunk 1: Piranha Plant Bonus Arena"
TALLTRUNK1LOG = "Tall Trunk 1: Carved Log Planet"
TALLTRUNK1DICEPIPE = "Tall Trunk 1: Dice Room"
TALLTRUNK1WOODCIRClE = "Tall Trunk 1: Wood Circle Planet"
TALLTRUNK2BIGTREE = "Tall Trunk 2: Big Tree Planet"
TALLTRUNK2PIRANHABONUS = "Tall Trunk 2: Piranha Plant Bonus Arena"
TALLTRUNK2SLIDE = "Tall Trunk 2: Log Slide"
TALLTRUNK2SLIDEND = "Tall Trunk 2: Tree Landing"
TALLTRUNK3PCOINSLIDE = "Tall Trunk 3: Purple Coin Slide"
TALLTRUNK3PCOINEND = "Tall Trunk 3: Purple Coin Tree Landing"
CLOUCOUR1LANDING = "Cloudy Court 1: Landing Planet"
CLOUCOUR1CYMBAL = "Cloudy Court 1: Cymbal Climb"
CLOUCOUR1TOWERS = "Cloudy Court 1: Ruined Towers"
CLOUCOUR1PARAGOOMBONUS = "Cloudy Court 1: Para-Goomba Bonus Arena"
CLOUCOUR3PCOINS = "Cloudy Court 3: Purple Pond"
CLOUCOUR1CASTLE = "Cloudy Court 1: Castle Wall"
CLOUCOUR2LANDING = "Cloudy Court 2: Cosmic Platforms Start"
CLOUCOUR2CASTLE1 = "Cloudy Court 2: Castle Wall 1"
CLOUCOUR2CASTLE2 = "Cloudy Court 2: Castle Wall 2"
CLOUCOUR2FINAL = "Cloudy Court 2: Final Tower"